// packages/react/adapter-radix/src/components/ColumnMenu.tsx
import { columnReorderKeyProps, useColumnDragState } from "@adapttable/react";
import {
  ACTIONS_COLUMN_KEY,
  columnMenuActions,
  type ColumnMenuItem,
  type ColumnMenuLabels,
  type ColumnMenuRow,
  columnMenuRows,
  type ColumnMenuSlotProps,
  type ColumnRenameEditorState,
  EyeIcon,
  filterColumnMenuRows,
  GripIcon,
  hideAllColumns,
  LiveRegion,
  nextPinSide,
  pinActionLabel,
  PinIcon,
  REORDER_COLUMN_KEY,
  showAllColumns,
  unpinAllColumns,
  type UseColumnLayoutResult,
  useColumnRenameEditor,
  useFeatureHost,
} from "@adapttable/react/adapter";
import {
  Button,
  Flex,
  IconButton,
  Popover,
  Separator,
  Text,
  TextField,
} from "@radix-ui/themes";
import { useRef, useState } from "react";

import { NativeSelect } from "./primitives";

const NOOP_RENAME = () => undefined;

function focusRenameInput(input: HTMLInputElement | null): void {
  input?.focus();
}

function ColumnRenameEditor({
  editor,
  labels,
}: Readonly<{
  editor: ColumnRenameEditorState;
  labels: ColumnMenuLabels;
}>) {
  if (!editor.editing) return null;
  return (
    <form
      data-adapttable-part="column-rename-form"
      style={{ display: "flex", flexDirection: "column", gap: 4 }}
      onSubmit={(event) => {
        event.preventDefault();
        editor.submit();
      }}
    >
      <Text
        as="label"
        htmlFor={editor.inputId}
        size="1"
        data-adapttable-part="column-rename-label"
      >
        {labels.columnName}
      </Text>
      <TextField.Root
        ref={focusRenameInput}
        id={editor.inputId}
        size="1"
        value={editor.draft}
        aria-invalid={editor.error ? true : undefined}
        aria-describedby={editor.error ? editor.errorId : undefined}
        data-adapttable-part="column-rename-input"
        onChange={(event) => editor.setDraft(event.currentTarget.value)}
        onBlur={editor.blur}
        onKeyDown={editor.onKeyDown}
      />
      {editor.error ? (
        <Text
          id={editor.errorId}
          role="alert"
          size="1"
          color="red"
          data-adapttable-part="column-rename-error"
        >
          {editor.error}
        </Text>
      ) : null}
      <Flex gap="1">
        <Button
          type="submit"
          size="1"
          data-adapttable-part="column-rename-save"
        >
          {labels.saveColumnName}
        </Button>
        <Button
          type="button"
          size="1"
          variant="soft"
          color="gray"
          data-adapttable-part="column-rename-cancel"
          onClick={editor.cancel}
        >
          {labels.cancelColumnRename}
        </Button>
      </Flex>
    </form>
  );
}

/** The shared Columns-menu contract, declared once in core. */
export type ColumnMenuProps<TRow> = ColumnMenuSlotProps<TRow> & {
  /** Fullscreen-safe target for the popover and nested choices. */
  container?: HTMLElement;
};

/** Eye toggle for one menu row (a data column or the actions entry). */
function VisibilityToggle({
  hidden,
  name,
  labels,
  onToggle,
  disabled = false,
}: Readonly<{
  hidden: boolean;
  name: string;
  labels: ColumnMenuLabels;
  onToggle: () => void;
  disabled?: boolean;
}>) {
  return (
    <IconButton
      size="1"
      variant="ghost"
      color="gray"
      aria-label={`${hidden ? labels.showColumn : labels.hideColumn}: ${name}`}
      aria-pressed={!hidden}
      disabled={disabled}
      onClick={onToggle}
    >
      <EyeIcon off={hidden} />
    </IconButton>
  );
}

/** Menu-row label, struck through while its column is hidden. */
function RowName({
  hidden,
  name,
}: Readonly<{ hidden: boolean; name: string }>) {
  return (
    <Text
      size="2"
      color={hidden ? "gray" : undefined}
      style={{
        flex: 1,
        textDecoration: hidden ? "line-through" : undefined,
      }}
    >
      {name}
    </Text>
  );
}

/** Pin toggle for one menu row; `label` names the action it performs next. */
function PinToggle({
  pinned,
  label,
  onClick,
  disabled = false,
}: Readonly<{
  pinned: boolean;
  label: string;
  onClick: () => void;
  disabled?: boolean;
}>) {
  return (
    <IconButton
      size="1"
      variant={pinned ? "solid" : "ghost"}
      color={pinned ? "teal" : "gray"}
      aria-label={label}
      disabled={disabled}
      onClick={onClick}
    >
      <PinIcon />
    </IconButton>
  );
}

function ColumnMenuRowItem<TRow>({
  row,
  layout,
  labels,
  drag,
  sortBy,
  sortDir,
  onSortColumn,
  onAutoSizeColumn,
  onFilterColumn,
  onRenameColumn,
  groupingPanel,
  dir,
  container,
}: Readonly<{
  row: ColumnMenuRow<TRow>;
  layout: UseColumnLayoutResult<TRow>;
  labels: ColumnMenuLabels;
  drag: ReturnType<typeof useColumnDragState>;
  sortBy?: string;
  sortDir?: "asc" | "desc";
  onSortColumn?: (key: string, dir: "asc" | "desc") => void;
  onAutoSizeColumn?: (key: string) => void;
  onFilterColumn?: (key: string) => void;
  onRenameColumn?: (key: string, name: string) => void;
  groupingPanel: ColumnMenuProps<TRow>["groupingPanel"];
  dir: ColumnMenuProps<TRow>["dir"];
  container?: HTMLElement;
}>) {
  const { key, name, hidden, pinned, index, canMove, canHide, canPin } = row;
  const [open, setOpen] = useState(false);
  const featureHost = useFeatureHost<TRow>();
  const rename = useColumnRenameEditor({
    key,
    name,
    onRename: onRenameColumn ?? NOOP_RENAME,
    requiredMessage: labels.columnNameRequired,
    renamedMessage: labels.columnRenamed,
  });
  const actions = columnMenuActions(row, {
    featureHost,
    labels,
    layout,
    sortBy,
    sortDir,
    onSortColumn,
    onAutoSizeColumn,
    onFilterColumn,
    onBeginRename: onRenameColumn ? rename.begin : undefined,
    groupingPanel,
  });
  const indicator = canMove ? drag.rowAttrs(key, index) : {};
  const edge = indicator["data-drop"];
  const edgeOffset = edge === "before" ? "2px" : "-2px";
  return (
    <div
      data-adapttable-part="column-menu-item"
      data-hidden={hidden || undefined}
      data-pinned={pinned}
    >
      <Flex
        gap="1"
        align="center"
        style={{
          cursor: canMove ? "grab" : "default",
          padding: "2px 0",
          opacity: "data-dragging" in indicator ? 0.4 : undefined,
          boxShadow: edge
            ? `inset 0 ${edgeOffset} 0 0 var(--accent-9)`
            : undefined,
        }}
        {...(canMove
          ? {
              ...drag.rowDragProps(key, index),
              ...drag.dropProps(index, layout.move),
              ...indicator,
            }
          : {})}
      >
        <IconButton
          size="1"
          variant="ghost"
          color="gray"
          disabled={!canMove}
          style={{ cursor: canMove ? "grab" : "default" }}
          {...(canMove
            ? columnReorderKeyProps(
                key,
                index,
                layout.move,
                `${labels.moveStart} / ${labels.moveEnd}: ${name}`
              )
            : {})}
        >
          <GripIcon />
        </IconButton>
        <VisibilityToggle
          hidden={hidden}
          name={name}
          labels={labels}
          disabled={!canHide}
          onToggle={() => layout.toggleVisible(key)}
        />
        <RowName hidden={hidden} name={name} />
        <PinToggle
          pinned={Boolean(pinned)}
          label={`${pinActionLabel(pinned, labels)}: ${name}`}
          disabled={!canPin}
          onClick={() => layout.setPinned(key, nextPinSide(pinned))}
        />
        <IconButton
          size="1"
          variant="ghost"
          color="gray"
          data-adapttable-part="column-menu-more"
          aria-expanded={open}
          aria-label={`${labels.columnActions}: ${name}`}
          onClick={() => setOpen((value) => !value)}
        >
          ⋯
        </IconButton>
      </Flex>
      {open ? (
        <Flex
          direction="column"
          data-adapttable-part="column-menu-submenu"
          gap="1"
        >
          {actions.map((action: ColumnMenuItem) =>
            "kind" in action ? (
              <Flex
                key={action.id}
                direction="column"
                gap="1"
                data-adapttable-part="column-menu-choice"
              >
                <Text as="span" size="1" color="gray">
                  {action.label}
                </Text>
                <NativeSelect
                  size="1"
                  aria-label={action.label}
                  value={action.value}
                  options={action.options}
                  disabled={action.disabled}
                  dir={dir}
                  container={container}
                  width="100%"
                  onValueChange={action.onChange}
                />
              </Flex>
            ) : (
              <Button
                key={action.id}
                size="1"
                variant="ghost"
                color="gray"
                data-adapttable-part="column-menu-action"
                disabled={
                  action.disabled || (action.id === "rename" && rename.editing)
                }
                style={{ alignSelf: "flex-start" }}
                onClick={() => {
                  action.run();
                  if (action.id !== "rename") setOpen(false);
                }}
              >
                {action.label}
              </Button>
            )
          )}
          <ColumnRenameEditor editor={rename} labels={labels} />
        </Flex>
      ) : null}
      <LiveRegion part="column-rename-announcer" statusRole={false}>
        {rename.announcement}
      </LiveRegion>
    </div>
  );
}

/**
 * Radix Themes column-management popover: per-column drag grip (reorder), eye
 * (show/hide), and pin toggle — plus, when the table has row actions, a
 * trailing entry that hides or end-pins the injected actions column.
 */
export function ColumnMenu<TRow>({
  allColumns,
  layout,
  labels,
  hasRowActions = false,
  hasRowReorder = false,
  onAutoSize,
  onAutoSizeColumn,
  onSortColumn,
  onFilterColumn,
  onRenameColumn,
  sortBy,
  sortDir,
  dir,
  groupingPanel,
  container,
}: Readonly<ColumnMenuProps<TRow>>) {
  const drag = useColumnDragState();
  const [query, setQuery] = useState("");
  const rows = filterColumnMenuRows(columnMenuRows(allColumns, layout), query);
  const actionsHidden = layout.isHidden(ACTIONS_COLUMN_KEY);
  // Rows own their own editor state. Rather than lift it through every row,
  // the menu asks its own content whether an editor is mounted — the part
  // name is the same public contract every kit renders.
  const contentRef = useRef<HTMLDivElement | null>(null);
  const actionsPinned = layout.state.pinned[ACTIONS_COLUMN_KEY] === "end";
  const reorderHidden = layout.isHidden(REORDER_COLUMN_KEY);
  const reorderPinned = layout.state.pinned[REORDER_COLUMN_KEY] !== undefined;
  return (
    <Popover.Root>
      <Popover.Trigger>
        <Button
          size="2"
          variant="outline"
          data-adapttable-part="column-menu-button"
        >
          {labels.columns}
        </Button>
      </Popover.Trigger>
      <Popover.Content
        ref={contentRef}
        container={container}
        aria-label={labels.columns}
        align="end"
        side="bottom"
        // Collision handling stays on: a panel wider than the space
        // beside its trigger otherwise runs off the edge on a narrow
        // viewport and clips its own labels.
        minWidth="260px"
        dir={dir}
        maxHeight="min(70vh, 480px)"
        style={{ overflowY: "auto", zIndex: 10050 }}
        // Radix dismisses on a capture-phase document listener, so it sees
        // Escape before the rename editor can mark it handled — one key
        // cancelled the edit and closed the whole menu with it. While an
        // editor is open the innermost control answers, and the menu does
        // not; the next Escape closes the menu as usual.
        onEscapeKeyDown={(event) => {
          const editing = contentRef.current?.querySelector(
            '[data-adapttable-part="column-rename-input"]'
          );
          if (editing) event.preventDefault();
        }}
      >
        <Flex direction="column" gap="1">
          <Text
            size="1"
            weight="bold"
            color="gray"
            style={{ textTransform: "uppercase", letterSpacing: "0.06em" }}
          >
            {labels.columns}
          </Text>
          <TextField.Root
            type="search"
            size="1"
            data-adapttable-part="column-menu-search"
            placeholder={labels.searchColumns}
            aria-label={labels.searchColumns}
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
          <Flex gap="1" wrap="wrap" data-adapttable-part="column-menu-bulk">
            <Button
              size="1"
              variant="ghost"
              color="gray"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => showAllColumns(rows, layout)}
            >
              {labels.showAllColumns}
            </Button>
            <Button
              size="1"
              variant="ghost"
              color="gray"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => hideAllColumns(rows, layout)}
            >
              {labels.hideAllColumns}
            </Button>
            <Button
              size="1"
              variant="ghost"
              color="gray"
              data-adapttable-part="column-menu-bulk-button"
              onClick={() => unpinAllColumns(rows, layout)}
            >
              {labels.unpinAllColumns}
            </Button>
          </Flex>
          {rows.map((row) => (
            <ColumnMenuRowItem
              key={row.key}
              row={row}
              layout={layout}
              labels={labels}
              drag={drag}
              sortBy={sortBy}
              sortDir={sortDir}
              onSortColumn={onSortColumn}
              onAutoSizeColumn={onAutoSizeColumn}
              onFilterColumn={onFilterColumn}
              onRenameColumn={onRenameColumn}
              groupingPanel={groupingPanel}
              dir={dir}
              container={container}
            />
          ))}
          {(hasRowReorder || hasRowActions) && <Separator my="1" size="4" />}
          {hasRowReorder && (
            <div data-adapttable-part="column-menu-item" data-reorder="">
              <Flex gap="1" align="center">
                <VisibilityToggle
                  hidden={reorderHidden}
                  name={labels.reorderRow}
                  labels={labels}
                  onToggle={() => layout.toggleVisible(REORDER_COLUMN_KEY)}
                />
                <RowName hidden={reorderHidden} name={labels.reorderRow} />
                <PinToggle
                  pinned={reorderPinned}
                  label={`${reorderPinned ? labels.unpin : labels.pinStart}: ${labels.reorderRow}`}
                  onClick={() =>
                    layout.setPinned(
                      REORDER_COLUMN_KEY,
                      reorderPinned ? undefined : "start"
                    )
                  }
                />
              </Flex>
            </div>
          )}
          {hasRowActions && (
            <Flex gap="1" align="center">
              <VisibilityToggle
                hidden={actionsHidden}
                name={labels.actions}
                labels={labels}
                onToggle={() => layout.toggleVisible(ACTIONS_COLUMN_KEY)}
              />
              <RowName hidden={actionsHidden} name={labels.actions} />
              <PinToggle
                pinned={actionsPinned}
                label={`${actionsPinned ? labels.unpin : labels.pinEnd}: ${labels.actions}`}
                onClick={() =>
                  layout.setPinned(
                    ACTIONS_COLUMN_KEY,
                    actionsPinned ? undefined : "end"
                  )
                }
              />
            </Flex>
          )}
          <Separator my="1" size="4" />
          <Button
            size="1"
            variant="ghost"
            color="gray"
            style={{ alignSelf: "flex-start" }}
            onClick={onAutoSize}
          >
            {labels.autoSizeColumns}
          </Button>
          <Button
            size="1"
            variant="ghost"
            color="gray"
            style={{ alignSelf: "flex-start" }}
            onClick={() => layout.reset()}
          >
            {labels.resetColumns}
          </Button>
        </Flex>
      </Popover.Content>
    </Popover.Root>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/columnMenu.ts
/**
 * The Columns menu: a disclosure button and a panel where each column has a
 * reorder grip, an eye toggle, a pin toggle and a submenu of actions — drawn
 * with native controls, over the menu model in `@adapttable/angular`.
 */
import {
  ACTIONS_COLUMN_KEY,
  AdaptAttrs,
  AdaptIcon,
  AdaptLiveRegion,
  ADAPTTABLE_SLOT_TABLE,
  type ColumnDrag,
  type ColumnLayout,
  columnMenuActions,
  type ColumnMenuChoice,
  type ColumnMenuItem,
  type ColumnMenuRow,
  columnMenuRows,
  type ColumnMenuSlotProps,
  eyeIcon,
  filterColumnMenuRows,
  GRIP_ICON,
  hideAllColumns,
  injectColumnDrag,
  injectColumnRenameEditor,
  nextPinSide,
  PIN_ICON,
  pinActionLabel,
  REORDER_COLUMN_KEY,
  showAllColumns,
  unpinAllColumns,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  inject,
  Injector,
  input,
  signal,
  viewChild,
} from "@angular/core";

import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";

/** The menu's props, with the row type erased as every slot erases it. */
type MenuProps = ColumnMenuSlotProps<never>;

const NOOP_RENAME = (): void => undefined;

/** Whether a submenu item is a choice rather than a plain action. */
function isChoice(item: ColumnMenuItem): item is ColumnMenuChoice {
  return "kind" in item && item.kind === "choice";
}

/**
 * One column's row: grip, eye, name, pin, and the "more" submenu with the
 * rename editor.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-row",
  imports: [AdaptAttrs, AdaptIcon, AdaptLiveRegion],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let r = row();
    @let p = props();
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-hidden]="r.hidden ? '' : null"
      [attr.data-pinned]="r.pinned ?? null"
      [style.cursor]="r.canMove ? 'grab' : 'default'"
      [adaptAttrs]="
        r.canMove ? drag().rowAttrs(r.key, r.index, p.layout.move) : {}
      "
    >
      <span
        data-adapttable-part="column-menu-grip"
        [attr.aria-disabled]="r.canMove ? null : 'true'"
        [adaptAttrs]="
          r.canMove
            ? drag().gripAttrs(
                r.key,
                r.index,
                p.layout.move,
                p.labels.moveStart + ' / ' + p.labels.moveEnd + ': ' + r.name
              )
            : {}
        "
        ><svg [adaptIcon]="gripIcon"></svg
      ></span>
      <button
        type="button"
        data-adapttable-part="column-menu-visibility"
        [attr.data-active]="r.hidden ? null : ''"
        [attr.aria-pressed]="!r.hidden"
        [attr.aria-label]="
          (r.hidden ? p.labels.showColumn : p.labels.hideColumn) + ': ' + r.name
        "
        [disabled]="!r.canHide"
        (click)="p.layout.toggleVisible(r.key)"
      >
        <svg [adaptIcon]="r.hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        data-adapttable-part="column-menu-label"
        [attr.data-hidden]="r.hidden ? '' : null"
        >{{ r.name }}</span
      >
      <button
        type="button"
        data-adapttable-part="column-menu-pin"
        [attr.data-active]="r.pinned !== undefined ? '' : null"
        [attr.aria-pressed]="r.pinned !== undefined"
        [attr.aria-label]="pinLabel(r, p) + ': ' + r.name"
        [disabled]="!r.canPin"
        (click)="p.layout.setPinned(r.key, nextPin(r))"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
      <button
        type="button"
        data-adapttable-part="column-menu-more"
        [attr.aria-expanded]="open()"
        [attr.aria-label]="p.labels.columnActions + ': ' + r.name"
        (click)="open.set(!open())"
      >
        ⋯
      </button>
      @if (open()) {
        <div data-adapttable-part="column-menu-submenu">
          @for (item of actions(); track item.id) {
            @if (asChoice(item); as choice) {
              <label data-adapttable-part="column-menu-choice">
                <span data-adapttable-part="column-menu-choice-label">{{
                  choice.label
                }}</span>
                <select
                  data-adapttable-part="column-menu-choice-select"
                  [attr.aria-label]="choice.label"
                  [value]="choice.value"
                  [disabled]="choice.disabled"
                  (change)="choice.onChange($any($event.target).value)"
                >
                  @for (option of choice.options; track option.value) {
                    <option [value]="option.value">{{ option.label }}</option>
                  }
                </select>
              </label>
            } @else {
              <button
                type="button"
                data-adapttable-part="column-menu-action"
                [disabled]="
                  asAction(item).disabled ||
                  (item.id === 'rename' && rename.editing())
                "
                (click)="runAction(item)"
              >
                {{ item.label }}
              </button>
            }
          }
          @if (rename.editing()) {
            <form
              data-adapttable-part="column-rename-form"
              (submit)="$event.preventDefault(); rename.submit()"
            >
              <label
                data-adapttable-part="column-rename-label"
                [attr.for]="rename.inputId"
                >{{ p.labels.columnName }}</label
              >
              <input
                data-adapttable-part="column-rename-input"
                [adaptAttrs]="rename.inputAttrs()"
              />
              @if (rename.error(); as error) {
                <span
                  data-adapttable-part="column-rename-error"
                  role="alert"
                  [attr.id]="rename.errorId"
                  >{{ error }}</span
                >
              }
              <button type="submit" data-adapttable-part="column-rename-save">
                {{ p.labels.saveColumnName }}
              </button>
              <button
                type="button"
                data-adapttable-part="column-rename-cancel"
                (click)="rename.cancel()"
              >
                {{ p.labels.cancelColumnRename }}
              </button>
            </form>
          }
        </div>
      }
      <div
        [adaptLiveRegion]="rename.announcement()"
        part="column-rename-announcer"
      ></div>
    </div>
  `,
})
export class AdaptColumnMenuRow {
  /** The row. */
  readonly row = input.required<ColumnMenuRow<never>>();
  /** The menu's props. */
  readonly props = input.required<MenuProps>();
  /** The menu's drag state. */
  readonly drag = input.required<ColumnDrag>();

  protected readonly open = signal(false);
  protected readonly gripIcon = GRIP_ICON;
  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
  private readonly table = inject(ADAPTTABLE_SLOT_TABLE);

  protected readonly rename = injectColumnRenameEditor({
    column: computed(() => ({
      key: this.row().key,
      name: this.row().name,
      onRename: this.props().onRenameColumn ?? NOOP_RENAME,
      requiredMessage: this.props().labels.columnNameRequired,
      renamedMessage: this.props().labels.columnRenamed,
    })),
  });

  protected readonly actions = computed(() => {
    const props = this.props();
    return columnMenuActions(this.row(), {
      featureHost: this.table.featureHost as never,
      labels: props.labels,
      layout: props.layout,
      sortBy: props.sortBy,
      sortDir: props.sortDir,
      onSortColumn: props.onSortColumn,
      onAutoSizeColumn: props.onAutoSizeColumn,
      onFilterColumn: props.onFilterColumn,
      onBeginRename: props.onRenameColumn ? this.rename.begin : undefined,
      groupingPanel: props.groupingPanel,
    });
  });

  protected pinLabel(row: ColumnMenuRow<never>, props: MenuProps): string {
    return pinActionLabel(row.pinned, props.labels);
  }

  protected nextPin(row: ColumnMenuRow<never>): ReturnType<typeof nextPinSide> {
    return nextPinSide(row.pinned);
  }

  protected asChoice(item: ColumnMenuItem): ColumnMenuChoice | undefined {
    return isChoice(item) ? item : undefined;
  }

  protected asAction(item: ColumnMenuItem): { disabled: boolean } {
    return item;
  }

  protected runAction(item: ColumnMenuItem): void {
    if (isChoice(item)) return;
    item.run();
    if (item.id !== "rename") this.open.set(false);
  }
}

/**
 * A reserved column's row — row actions or the reorder grip — with its eye
 * and a one-click pin to the edge it always sits at.
 *
 * @internal
 */
@Component({
  selector: "adapt-column-menu-edge-row",
  imports: [AdaptIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let hidden = layout().isHidden(columnKey());
    @let pinned = layout().state.pinned[columnKey()] !== undefined;
    <div
      data-adapttable-part="column-menu-item"
      [attr.data-actions]="side() === 'end' ? '' : null"
      [attr.data-reorder]="side() === 'start' ? '' : null"
      [attr.data-hidden]="hidden ? '' : null"
      [attr.data-pinned]="pinned ? side() : null"
    >
      <button
        type="button"
        data-adapttable-part="column-menu-visibility"
        [attr.data-active]="hidden ? null : ''"
        [attr.aria-pressed]="!hidden"
        [attr.aria-label]="(hidden ? showLabel() : hideLabel()) + ': ' + name()"
        (click)="layout().toggleVisible(columnKey())"
      >
        <svg [adaptIcon]="hidden ? eyeOff : eyeOn"></svg>
      </button>
      <span
        data-adapttable-part="column-menu-label"
        [attr.data-hidden]="hidden ? '' : null"
        >{{ name() }}</span
      >
      <button
        type="button"
        data-adapttable-part="column-menu-pin"
        [attr.data-active]="pinned ? '' : null"
        [attr.aria-pressed]="pinned"
        [attr.aria-label]="(pinned ? unpinLabel() : pinLabel()) + ': ' + name()"
        (click)="layout().setPinned(columnKey(), pinned ? undefined : side())"
      >
        <svg [adaptIcon]="pinIcon"></svg>
      </button>
    </div>
  `,
})
export class AdaptColumnMenuEdgeRow {
  /** The column layout. */
  readonly layout = input.required<ColumnLayout<never>>();
  /** The reserved column's key. */
  readonly columnKey = input.required<string>();
  /** The edge it pins to. */
  readonly side = input.required<"start" | "end">();
  /** Its name. */
  readonly name = input.required<string>();
  /** "Show column". */
  readonly showLabel = input.required<string>();
  /** "Hide column". */
  readonly hideLabel = input.required<string>();
  /** "Pin to start" or "Pin to end". */
  readonly pinLabel = input.required<string>();
  /** "Unpin". */
  readonly unpinLabel = input.required<string>();

  protected readonly pinIcon = PIN_ICON;
  protected readonly eyeOn = eyeIcon(false);
  protected readonly eyeOff = eyeIcon(true);
}

/**
 * The Columns menu in the toolbar.
 *
 * @public
 */
@Component({
  selector: "adapt-column-menu",
  imports: [AdaptColumnMenuRow, AdaptColumnMenuEdgeRow],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let p = props();
    <div #root data-adapttable-part="column-menu" style="position: relative">
      <button
        #trigger
        type="button"
        data-adapttable-part="column-menu-button"
        aria-haspopup="true"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        {{ p.labels.columns }}
      </button>
      @if (popover.open()) {
        <fieldset
          #panel
          data-adapttable-part="column-menu-panel"
          [attr.aria-label]="p.labels.columns"
          [attr.dir]="p.dir ?? null"
          [style]="panelStyle"
        >
          <div data-adapttable-part="column-menu-header">
            <span data-adapttable-part="column-menu-title">{{
              p.labels.columns
            }}</span>
          </div>
          <input
            type="search"
            data-adapttable-part="column-menu-search"
            [attr.placeholder]="p.labels.searchColumns"
            [attr.aria-label]="p.labels.searchColumns"
            [value]="query()"
            (input)="query.set($any($event.target).value)"
          />
          <div data-adapttable-part="column-menu-bulk">
            <button
              type="button"
              data-adapttable-part="column-menu-bulk-button"
              (click)="showAll()"
            >
              {{ p.labels.showAllColumns }}
            </button>
            <button
              type="button"
              data-adapttable-part="column-menu-bulk-button"
              (click)="hideAll()"
            >
              {{ p.labels.hideAllColumns }}
            </button>
            <button
              type="button"
              data-adapttable-part="column-menu-bulk-button"
              (click)="unpinAll()"
            >
              {{ p.labels.unpinAllColumns }}
            </button>
          </div>
          @for (row of rows(); track row.key) {
            <adapt-column-menu-row [row]="row" [props]="p" [drag]="drag" />
          }
          @if (p.hasRowReorder || p.hasRowActions) {
            <hr data-adapttable-part="column-menu-separator" />
          }
          @if (p.hasRowReorder) {
            <adapt-column-menu-edge-row
              [layout]="p.layout"
              [columnKey]="reorderKey"
              side="start"
              [name]="p.labels.reorderRow"
              [showLabel]="p.labels.showColumn"
              [hideLabel]="p.labels.hideColumn"
              [pinLabel]="p.labels.pinStart"
              [unpinLabel]="p.labels.unpin"
            />
          }
          @if (p.hasRowActions) {
            <adapt-column-menu-edge-row
              [layout]="p.layout"
              [columnKey]="actionsKey"
              side="end"
              [name]="p.labels.actions"
              [showLabel]="p.labels.showColumn"
              [hideLabel]="p.labels.hideColumn"
              [pinLabel]="p.labels.pinEnd"
              [unpinLabel]="p.labels.unpin"
            />
          }
          <button
            type="button"
            data-adapttable-part="column-menu-auto-size"
            (click)="p.onAutoSize()"
          >
            {{ p.labels.autoSizeColumns }}
          </button>
          <button
            type="button"
            data-adapttable-part="column-menu-reset"
            (click)="p.layout.reset()"
          >
            {{ p.labels.resetColumns }}
          </button>
        </fieldset>
      }
    </div>
  `,
})
export class AdaptColumnMenu {
  /** The slot's props. */
  readonly props = input.required<MenuProps>();

  protected readonly query = signal("");
  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly reorderKey = REORDER_COLUMN_KEY;
  protected readonly actionsKey = ACTIONS_COLUMN_KEY;
  protected readonly drag = injectColumnDrag();
  protected readonly rows = computed(() =>
    filterColumnMenuRows(
      columnMenuRows(this.props().allColumns, this.props().layout),
      this.query()
    )
  );

  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  private readonly trigger = viewChild<ElementRef<HTMLElement>>("trigger");
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.trigger()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    inject(Injector)
  );

  protected showAll(): void {
    showAllColumns(this.rows(), this.props().layout);
  }

  protected hideAll(): void {
    hideAllColumns(this.rows(), this.props().layout);
  }

  protected unpinAll(): void {
    unpinAllColumns(this.rows(), this.props().layout);
  }
}
