// packages/react/adapter-mui/src/components/EditableCell.tsx
import {
  type ColumnDef,
  type EditableCellEditing,
  type EditableCellEditorCtrl,
  EditableCellGate,
} from "@adapttable/react";
import {
  commitBooleanDraft,
  editorBusyProps,
  editorInputType,
  editorValidationProps,
  isBooleanEditor,
  isDraftChecked,
  isMultiSelectEditor,
  isSelectEditor,
  multiDraftFromSelect,
  readMultiDraft,
  stopEditKeys,
} from "@adapttable/react/adapter";
import { Checkbox, MenuItem, TextField } from "@mui/material";
import type { KeyboardEvent, ReactElement, ReactNode } from "react";

import { editableCellSlots } from "./kitControls";

/** MUI text / number / select editor for the active cell. */
export function MuiCellEditor({
  ctrl,
  label,
}: Readonly<{
  ctrl: EditableCellEditorCtrl;
  label: string;
}>): ReactElement {
  const onKeyDown = (event: KeyboardEvent) => {
    ctrl.onEditorKeyDown(event);
    stopEditKeys(event);
  };

  if (isBooleanEditor(ctrl.editor)) {
    const inputSlot = {
      ref: ctrl.focusRef,
      "aria-label": label,
      "data-adapttable-part": "edit-cell-editor",
      ...editorValidationProps(ctrl),
    };
    return (
      <Checkbox
        slotProps={{ input: inputSlot }}
        checked={isDraftChecked(ctrl.draft)}
        onChange={(_, checked) => commitBooleanDraft(ctrl, checked)}
        onKeyDown={onKeyDown}
      />
    );
  }

  if (isMultiSelectEditor(ctrl.editor)) {
    return (
      <TextField
        inputRef={ctrl.focusRef}
        select
        size="small"
        fullWidth
        value={readMultiDraft(ctrl.draft)}
        onKeyDown={onKeyDown}
        onBlur={ctrl.commitOnBlur}
        data-adapttable-part="edit-cell-editor"
        slotProps={{
          select: {
            multiple: true,
            native: true,
            onChange: (event) => {
              const select = event.target as unknown as HTMLSelectElement;
              ctrl.setDraft(multiDraftFromSelect(select));
            },
          },
          htmlInput: { "aria-label": label, ...editorBusyProps(ctrl) },
        }}
      >
        {ctrl.selectOptions.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </TextField>
    );
  }

  if (isSelectEditor(ctrl.editor)) {
    return (
      <TextField
        inputRef={ctrl.focusRef}
        select
        size="small"
        fullWidth
        value={ctrl.draft}
        onChange={(event) => ctrl.setDraft(event.target.value)}
        onKeyDown={onKeyDown}
        onBlur={ctrl.commitOnBlur}
        error={ctrl.conflict === true ? false : ctrl.error !== undefined}
        helperText={ctrl.conflict === true ? undefined : ctrl.error}
        data-adapttable-part="edit-cell-editor"
        slotProps={{
          htmlInput: { "aria-label": label, ...editorBusyProps(ctrl) },
        }}
      >
        {ctrl.selectOptions.map((option) => (
          <MenuItem key={option.value} value={option.value}>
            {option.label}
          </MenuItem>
        ))}
      </TextField>
    );
  }

  return (
    <TextField
      inputRef={ctrl.focusRef}
      size="small"
      fullWidth
      type={editorInputType(ctrl.editor)}
      value={ctrl.draft}
      onChange={(event) => ctrl.setDraft(event.target.value)}
      onKeyDown={onKeyDown}
      onBlur={ctrl.commitOnBlur}
      error={ctrl.conflict === true ? false : ctrl.error !== undefined}
      helperText={ctrl.conflict === true ? undefined : ctrl.error}
      slotProps={{
        htmlInput: {
          "aria-label": label,
          "data-adapttable-part": "edit-cell-editor",
          ...editorBusyProps(ctrl),
        },
      }}
    />
  );
}

/** Opt-in editable cell — pass-through when `editing` is omitted. */
export function EditableDataCell<TRow>(props: {
  readonly editing: EditableCellEditing<TRow> | undefined;
  readonly row: TRow;
  readonly column: ColumnDef<TRow>;
  readonly rowId: string;
  readonly rows: readonly TRow[];
  readonly columns: readonly ColumnDef<TRow>[];
  readonly rowKey: (row: TRow) => string;
  readonly editLabel: string;
  /** `labels.undoEdit` — the control a failed save offers. */
  readonly undoLabel?: string;
  /**
   * What the cell shows when nothing is being edited. The binding resolves it
   * — the row's precomputed display, the column's `Cell`, or its accessor —
   * so the accessor runs in this cell's own memo scope.
   */
  readonly display: ReactNode;
}): ReactElement {
  return (
    <EditableCellGate
      kitRendersError
      editing={props.editing}
      row={props.row}
      column={props.column}
      rowId={props.rowId}
      rows={props.rows}
      columns={props.columns}
      rowKey={props.rowKey}
      editLabel={props.editLabel}
      undoLabel={props.undoLabel}
      display={props.display}
      slots={editableCellSlots}
      renderEditor={(ctrl) => (
        <MuiCellEditor ctrl={ctrl} label={props.editLabel} />
      )}
    />
  );
}

// packages/angular/adapter-angular-unstyled/src/components/editableCell.ts
/**
 * Native editable cell — the kit fill for {@link EDITABLE_CELL}.
 */
import {
  AdaptEditableCellGate,
  type ColumnDef,
  commitBooleanDraft,
  type EditableCellActivateProps,
  type EditableCellButtonProps,
  type EditableCellEditing,
  type EditableCellEditorCtrl,
  type EditableCellSlotProps,
  type EditableCellSlots,
  editorInputType,
  editorValidationProps,
  isBooleanEditor,
  isDraftChecked,
  isMultiSelectEditor,
  isSelectEditor,
  multiDraftFromSelect,
  readMultiDraft,
  resolveEditableCellDisplay,
  stopEditKeys,
} from "@adapttable/angular";
import {
  type AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  type ElementRef,
  input,
  viewChild,
} from "@angular/core";

@Component({
  selector: "adapt-edit-cell-activate",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <button
      #btn
      type="button"
      data-adapttable-part="edit-cell-activate"
      [attr.title]="p.title"
      [attr.data-dirty]="p.dirty ? '' : null"
      [attr.data-save]="p.saveStatus ?? null"
      [attr.aria-busy]="p.saveStatus === 'saving' ? true : null"
      [class]="p.className"
      style="all: unset; box-sizing: border-box; display: block; width: 100%; cursor: text; text-align: inherit"
      (dblclick)="p.onDoubleClick($event)"
      (click)="p.onClick($event)"
      (keydown)="p.onKeyDown($event)"
    >
      {{ p.display }}
    </button>
  `,
})
class AdaptEditCellActivate implements AfterViewInit {
  readonly props = input.required<EditableCellActivateProps>();
  private readonly btn = viewChild<ElementRef<HTMLButtonElement>>("btn");
  ngAfterViewInit(): void {
    this.props().activateRef(this.btn()?.nativeElement ?? null);
  }
}

@Component({
  selector: "adapt-edit-cell-button",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <button
      type="button"
      [attr.data-adapttable-part]="p.part"
      [class]="p.className"
      (mousedown)="p.onMouseDown?.($event)"
      (click)="p.onClick($event)"
    >
      {{ p.label }}
    </button>
  `,
})
class AdaptEditCellButton {
  readonly props = input.required<EditableCellButtonProps>();
}

@Component({
  selector: "adapt-native-cell-editor",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    @let v = editorValidationProps(p);
    @if (isBooleanEditor(p.editor)) {
      <input
        #el
        data-adapttable-part="edit-cell-editor"
        type="checkbox"
        [attr.aria-label]="p.label"
        [attr.aria-invalid]="v['aria-invalid'] ?? null"
        [attr.aria-describedby]="v['aria-describedby'] ?? null"
        [attr.data-conflict]="v['data-conflict'] ?? null"
        [checked]="isDraftChecked(p.draft)"
        (change)="commitBoolean($any($event.target).checked)"
        (keydown)="onKeyDown($event)"
      />
    } @else if (isMultiSelectEditor(p.editor)) {
      <select
        #el
        data-adapttable-part="edit-cell-editor"
        multiple
        [attr.aria-label]="p.label"
        [attr.aria-invalid]="v['aria-invalid'] ?? null"
        [attr.aria-describedby]="v['aria-describedby'] ?? null"
        (change)="p.setDraft(multiDraftFromSelect($any($event.target)))"
        (keydown)="onKeyDown($event)"
        (blur)="p.commitOnBlur()"
      >
        @for (option of p.selectOptions; track option.value) {
          <option
            [value]="option.value"
            [selected]="readMultiDraft(p.draft).includes(option.value)"
          >
            {{ option.label }}
          </option>
        }
      </select>
    } @else if (isSelectEditor(p.editor)) {
      <select
        #el
        data-adapttable-part="edit-cell-editor"
        [attr.aria-label]="p.label"
        [attr.aria-invalid]="v['aria-invalid'] ?? null"
        [attr.aria-describedby]="v['aria-describedby'] ?? null"
        [value]="p.draft"
        (change)="p.setDraft($any($event.target).value)"
        (keydown)="onKeyDown($event)"
        (blur)="p.commitOnBlur()"
      >
        @for (option of p.selectOptions; track option.value) {
          <option [value]="option.value">{{ option.label }}</option>
        }
      </select>
    } @else {
      <input
        #el
        data-adapttable-part="edit-cell-editor"
        [attr.aria-label]="p.label"
        [attr.aria-invalid]="v['aria-invalid'] ?? null"
        [attr.aria-describedby]="v['aria-describedby'] ?? null"
        [type]="editorInputType(p.editor)"
        [value]="p.draft"
        (input)="p.setDraft($any($event.target).value)"
        (keydown)="onKeyDown($event)"
        (blur)="p.commitOnBlur()"
      />
    }
  `,
})
class AdaptNativeCellEditor implements AfterViewInit {
  readonly props = input.required<EditableCellEditorCtrl>();
  private readonly el = viewChild<ElementRef<HTMLElement>>("el");

  protected readonly editorValidationProps = editorValidationProps;
  protected readonly isBooleanEditor = isBooleanEditor;
  protected readonly isDraftChecked = isDraftChecked;
  protected readonly isMultiSelectEditor = isMultiSelectEditor;
  protected readonly isSelectEditor = isSelectEditor;
  protected readonly editorInputType = editorInputType;
  protected readonly readMultiDraft = readMultiDraft;
  protected readonly multiDraftFromSelect = multiDraftFromSelect;

  ngAfterViewInit(): void {
    this.props().focusRef(this.el()?.nativeElement ?? null);
  }

  protected commitBoolean(checked: boolean): void {
    commitBooleanDraft(this.props(), checked);
  }

  protected onKeyDown(event: KeyboardEvent): void {
    this.props().onEditorKeyDown(event);
    stopEditKeys(event);
  }
}

const SLOTS: EditableCellSlots = {
  Activate: AdaptEditCellActivate,
  Button: AdaptEditCellButton,
};

/**
 * Opt-in editable cell — pass-through when `editing` is omitted. Fills
 * {@link EDITABLE_CELL}.
 *
 * @public
 */
@Component({
  selector: "adapt-editable-cell",
  imports: [AdaptEditableCellGate],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <adapt-editable-cell-gate
      [editing]="editing()"
      [row]="p.row"
      [column]="column()"
      [rowId]="p.rowId"
      [rows]="p.rows"
      [columns]="columns()"
      [rowKey]="p.rowKey"
      [editLabel]="p.editLabel"
      [undoLabel]="p.undoLabel"
      [display]="resolvedDisplay()"
      [editor]="editor"
      [slots]="slots"
    />
  `,
})
export class AdaptEditableCell<TRow> {
  /** Slot props from the table's editable-cell fill. */
  readonly props = input.required<EditableCellSlotProps<TRow>>();

  protected readonly editor = AdaptNativeCellEditor;
  protected readonly slots = SLOTS;

  /**
   * Editing bundle from the slot — typed for the gate.
   *
   * @internal
   */
  protected editing(): EditableCellEditing<TRow> | undefined {
    return this.props().editing as EditableCellEditing<TRow> | undefined;
  }

  /**
   * Column from the slot — typed for the gate.
   *
   * @internal
   */
  protected column(): ColumnDef<TRow> {
    return this.props().column;
  }

  /**
   * Columns from the slot — typed for the gate.
   *
   * @internal
   */
  protected columns(): readonly ColumnDef<TRow>[] {
    return this.props().columns;
  }

  /**
   * Resolved display for the activate control — the precomputed display, the
   * column's accessor, or nothing when neither is set.
   *
   * @internal
   */
  protected resolvedDisplay(): unknown {
    const p = this.props();
    return resolveEditableCellDisplay(
      p.display,
      p.column,
      () => undefined,
      p.row
    );
  }
}

export type { EditableCellEditing };
