// packages/react/adapter-antd/src/components/RowActionButtons.tsx
/** The trailing row-action buttons, shared by rows and cards. */
import {
  type ConfirmHandler,
  resolveDisabledReason,
  type RowAction,
  type RowActionsLayout,
  type RowActionsRenderer,
  runRowAction,
  type TableLabels,
  visibleRowActions,
} from "@adapttable/react/adapter";
import { Button, Dropdown, Tooltip } from "antd";
import type { ReactNode } from "react";

import { isDangerColor } from "../colors";
import { iconForRowAction, MoreVerticalIcon } from "../icons";

interface RowActionButtonsProps<TRow> {
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
  layout?: RowActionsLayout;
  render?: RowActionsRenderer<TRow>;
}

function ActionStrip<TRow>({
  row,
  actions,
  confirm,
  cancelLabel,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  cancelLabel: string;
}>): ReactNode {
  return (
    <>
      {actions.map((action) => {
        const reason = resolveDisabledReason(action.disabledReason?.(row));
        const disabled =
          reason !== undefined || (action.isDisabled?.(row) ?? false);
        const icon = iconForRowAction(action);
        return (
          <Tooltip key={action.key} title={reason ?? action.label}>
            <Button
              size="small"
              type="text"
              danger={isDangerColor(action.color)}
              disabled={disabled}
              icon={icon}
              title={reason}
              aria-label={action.label}
              data-adapttable-part="action-button"
              onClick={
                disabled
                  ? undefined
                  : (event) => {
                      event.stopPropagation();
                      runRowAction(action, row, confirm, cancelLabel);
                    }
              }
            >
              {icon ? undefined : action.label}
            </Button>
          </Tooltip>
        );
      })}
    </>
  );
}

/** Tags the dropdown surface with its part name for adapter styling hooks. */
function renderMenuSurface(menu: ReactNode): ReactNode {
  return <div data-adapttable-part="row-actions-menu">{menu}</div>;
}

function ActionMenu<TRow>({
  row,
  actions,
  confirm,
  labels,
}: Readonly<{
  row: TRow;
  actions: readonly RowAction<TRow>[];
  confirm: ConfirmHandler;
  labels: Required<TableLabels>;
}>): ReactNode {
  return (
    <Dropdown
      trigger={["click"]}
      popupRender={renderMenuSurface}
      menu={{
        items: actions.map((action) => {
          const reason = resolveDisabledReason(action.disabledReason?.(row));
          const disabled =
            reason !== undefined || (action.isDisabled?.(row) ?? false);
          return {
            key: action.key,
            label: action.label,
            icon: iconForRowAction(action),
            disabled,
            danger: isDangerColor(action.color),
            title: reason,
          };
        }),
        onClick: (info) => {
          // The menu sits inside the row, so the choice must not read as a
          // click on the row underneath it.
          info.domEvent.stopPropagation();
          const action = actions.find((item) => item.key === info.key);
          if (!action) return;
          runRowAction(action, row, confirm, labels.cancel);
        },
      }}
    >
      <Button
        size="small"
        type="text"
        aria-label={labels.rowActionsMenu}
        data-adapttable-part="row-actions-trigger"
        icon={<MoreVerticalIcon />}
        onClick={(event) => event.stopPropagation()}
      />
    </Dropdown>
  );
}

export function RowActionButtons<TRow>({
  row,
  actions,
  confirm,
  labels,
  layout,
  render,
}: Readonly<RowActionButtonsProps<TRow>>): ReactNode {
  const visible = visibleRowActions(actions, row);
  let content: ReactNode = null;
  if (render) {
    content = render({ row, actions, confirm, labels }) as ReactNode;
  } else if (visible.length > 0) {
    content =
      layout === "menu" ? (
        <ActionMenu
          row={row}
          actions={visible}
          confirm={confirm}
          labels={labels}
        />
      ) : (
        <ActionStrip
          row={row}
          actions={visible}
          confirm={confirm}
          cancelLabel={labels.cancel}
        />
      );
  }
  return content;
}

// packages/angular/adapter-angular-unstyled/src/components/rowActionButtons.ts
/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 */
import {
  type ConfirmHandler,
  resolveDisabledReason,
  type RowAction,
  type RowActionsLayout,
  runRowAction,
  type TableLabels,
  visibleRowActions,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  input,
  viewChild,
} from "@angular/core";

/**
 * One row's actions: a strip of buttons, or a menu behind a "more" button.
 *
 * @internal
 */
@Component({
  selector: "adapt-row-actions",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @if (layout() === "menu") {
      <details
        #menu
        data-adapttable-part="row-actions-menu"
        (pointerdown)="$event.stopPropagation()"
      >
        <summary
          data-adapttable-part="row-actions-trigger"
          [attr.aria-label]="labels().rowActionsMenu"
          (click)="$event.stopPropagation()"
        >
          ⋮
        </summary>
        @for (item of items(); track item.action.key) {
          <button
            type="button"
            data-adapttable-part="action-button"
            [attr.aria-label]="item.action.label"
            [attr.title]="item.reason ?? null"
            [attr.data-color]="item.action.color ?? null"
            [disabled]="item.disabled"
            (click)="run($event, item.action)"
          >
            {{ item.action.label }}
          </button>
        }
      </details>
    } @else {
      @for (item of items(); track item.action.key) {
        <button
          type="button"
          data-adapttable-part="action-button"
          [attr.aria-label]="item.action.label"
          [attr.title]="item.reason ?? null"
          [attr.data-color]="item.action.color ?? null"
          [disabled]="item.disabled"
          (click)="run($event, item.action)"
        >
          {{ item.action.label }}
        </button>
      }
    }
  `,
})
export class AdaptRowActions<TRow> {
  /** The row. */
  readonly row = input.required<TRow>();
  /** Its actions. */
  readonly actions = input.required<readonly RowAction<TRow>[]>();
  /** Asks before an action that declares a `confirm`. */
  readonly confirm = input.required<ConfirmHandler>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();
  /** A strip of buttons, or a menu. */
  readonly layout = input<RowActionsLayout | undefined>();

  private readonly menu = viewChild<ElementRef<HTMLDetailsElement>>("menu");

  protected readonly items = computed(() =>
    visibleRowActions(this.actions(), this.row()).map((action) => {
      const reason = resolveDisabledReason(action.disabledReason?.(this.row()));
      return {
        action,
        reason,
        disabled:
          reason !== undefined || (action.isDisabled?.(this.row()) ?? false),
      };
    })
  );

  protected run(event: Event, action: RowAction<TRow>): void {
    event.stopPropagation();
    this.menu()?.nativeElement.removeAttribute("open");
    runRowAction(action, this.row(), this.confirm(), this.labels().cancel);
  }
}
