// packages/react/adapter-unstyled/src/components/SavedViewsMenu.tsx
import { useSavedViews, type UseSavedViewsOptions } from "@adapttable/react";
import type { TableLabels } from "@adapttable/react/adapter";
import { type CSSProperties, useState } from "react";
import { createPortal } from "react-dom";

import type { DataTableClassNames } from "../types";
import { MENU_PANEL_STYLE, useMenuPopover } from "./menuPopover";

/**
 * Layout for a panel row: the name/input takes the space, the trailing
 * button keeps its size. The gap is structural — without it the two sit
 * flush, and no class hook can add space a consumer has not asked for.
 */
const ROW_STYLE: CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 6,
};

/**
 * The label strings the saved-views menu renders.
 *
 * @public
 */
export type SavedViewsLabels = Pick<
  Required<TableLabels>,
  "savedViews" | "saveView" | "viewName" | "deleteView"
>;

/**
 * Props for the saved-views menu: the views, and what may be done to them.
 *
 * @public
 */
export interface SavedViewsMenuProps {
  /** Wiring for core's `useSavedViews` — storage key, storage, adapter, urlKey. */
  options: UseSavedViewsOptions;
  /** Resolved labels, every key filled. */
  labels: SavedViewsLabels;
  /** Per-part classes. */
  classNames: DataTableClassNames;
}

/**
 * Saved-views popover: a disclosure button + a panel listing the saved views
 * (click applies one and closes; each has a delete button) above a save row
 * that captures the table's CURRENT state under a typed name. Built on core's
 * `useSavedViews`; closes on outside-click or Escape. Ships no styles —
 * target the `data-adapttable-part` hooks or the `views*` className slots.
 *
 * @public
 */
export function SavedViewsMenu({
  options,
  labels,
  classNames,
}: Readonly<SavedViewsMenuProps>) {
  const { views, save, apply, remove } = useSavedViews(options);
  const { open, setOpen, rootRef, triggerRef, panelRef } = useMenuPopover();
  const [name, setName] = useState("");
  const trimmed = name.trim();

  return (
    <div
      ref={rootRef}
      data-adapttable-part="views-menu"
      className={classNames.viewsMenu}
      style={{ position: "relative" }}
    >
      <button
        ref={triggerRef}
        type="button"
        aria-expanded={open}
        aria-haspopup="true"
        data-adapttable-part="views-button"
        data-active={open || undefined}
        className={classNames.viewsButton}
        style={{ flexShrink: 0, whiteSpace: "nowrap" }}
        onClick={() => setOpen((v) => !v)}
      >
        {labels.savedViews}
      </button>
      {open &&
        createPortal(
          <div
            ref={panelRef}
            data-adapttable-part="views-panel"
            className={classNames.viewsPanel}
            style={MENU_PANEL_STYLE}
          >
            {views.map((view) => (
              <div
                key={view.name}
                data-adapttable-part="views-row"
                className={classNames.viewsRow}
                style={ROW_STYLE}
              >
                <button
                  type="button"
                  data-adapttable-part="views-item"
                  className={classNames.viewsItem}
                  onClick={() => {
                    apply(view.name);
                    setOpen(false);
                  }}
                >
                  {view.name}
                </button>
                <button
                  type="button"
                  aria-label={`${labels.deleteView}: ${view.name}`}
                  data-adapttable-part="views-delete"
                  className={classNames.viewsDelete}
                  onClick={() => remove(view.name)}
                >
                  ×
                </button>
              </div>
            ))}
            <hr
              data-adapttable-part="views-divider"
              className={classNames.viewsDivider}
            />
            <div
              data-adapttable-part="views-save-row"
              className={classNames.viewsSaveRow}
              style={ROW_STYLE}
            >
              <input
                aria-label={labels.viewName}
                placeholder={labels.viewName}
                data-adapttable-part="views-input"
                className={classNames.viewsInput}
                value={name}
                onChange={(e) => setName(e.currentTarget.value)}
              />
              <button
                type="button"
                disabled={trimmed === ""}
                data-adapttable-part="views-save"
                className={classNames.viewsSave}
                onClick={() => {
                  save(trimmed);
                  setName("");
                }}
              >
                {labels.saveView}
              </button>
            </div>
          </div>,
          document.body
        )}
    </div>
  );
}

// packages/angular/adapter-angular-unstyled/src/components/savedViewsMenu.ts
/**
 * The saved-views menu: a button and a panel listing the saved views —
 * click one to apply it, or delete it — above a row that saves the table's
 * current state under a name.
 */
import {
  injectSavedViews,
  type SavedViewsControllerOptions,
  type SavedViewsSlotProps,
  type SavedViewsState,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  inject,
  Injector,
  input,
  type OnInit,
  signal,
  viewChild,
} from "@angular/core";

import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";

/**
 * The saved-views toolbar control.
 *
 * @internal
 */
@Component({
  selector: "adapt-saved-views-menu",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let l = props().labels;
    <div #root data-adapttable-part="views-menu" style="position: relative">
      <button
        #trigger
        type="button"
        aria-haspopup="true"
        data-adapttable-part="views-button"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        {{ l.savedViews }}
      </button>
      @if (popover.open()) {
        <div #panel data-adapttable-part="views-panel" [style]="panelStyle">
          @for (view of views()?.views() ?? []; track view.name) {
            <div data-adapttable-part="views-row" [style]="rowStyle">
              <button
                type="button"
                data-adapttable-part="views-item"
                (click)="apply(view.name)"
              >
                {{ view.name }}
              </button>
              <button
                type="button"
                data-adapttable-part="views-delete"
                [attr.aria-label]="l.deleteView + ': ' + view.name"
                (click)="views()?.remove(view.name)"
              >
                ×
              </button>
            </div>
          }
          <hr data-adapttable-part="views-divider" />
          <div data-adapttable-part="views-save-row" [style]="rowStyle">
            <input
              data-adapttable-part="views-input"
              [attr.aria-label]="l.viewName"
              [attr.placeholder]="l.viewName"
              [value]="name()"
              (input)="name.set($any($event.target).value)"
            />
            <button
              type="button"
              data-adapttable-part="views-save"
              [disabled]="trimmed() === ''"
              (click)="save()"
            >
              {{ l.saveView }}
            </button>
          </div>
        </div>
      }
    </div>
  `,
})
export class AdaptSavedViewsMenu implements OnInit {
  /** The slot's props. */
  readonly props =
    input.required<SavedViewsSlotProps<SavedViewsControllerOptions>>();

  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly rowStyle = {
    display: "flex",
    "align-items": "center",
    gap: "6px",
  };
  protected readonly name = signal("");
  protected readonly trimmed = computed(() => this.name().trim());
  /** The views, once the props say where they are kept. */
  protected readonly views = signal<SavedViewsState | undefined>(undefined);

  private readonly injector = inject(Injector);
  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  private readonly trigger = viewChild<ElementRef<HTMLElement>>("trigger");
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.trigger()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    this.injector
  );

  /** Open the views where the props say they are kept. */
  ngOnInit(): void {
    this.views.set(
      injectSavedViews({ ...this.props().options, injector: this.injector })
    );
  }

  protected apply(name: string): void {
    this.views()?.apply(name);
    this.popover.close();
  }

  protected save(): void {
    this.views()?.save(this.trimmed());
    this.name.set("");
  }
}
