// packages/angular/adapter-angular-unstyled/src/components/autoFilterForm.ts
/**
 * The auto-built filter form: one native field per definition — a text
 * field with its operator, a yes/no select, a select, a group of checkboxes,
 * a checklist, or an operator-first number or date range.
 */
import {
  AdaptChecklistChrome,
  booleanFilterFor,
  defaultFilterRegistry,
  type FilterDef,
  filterLabel,
  filterOpLabel,
  filterOptionsFor,
  type FilterOptionsState,
  type FilterTypeRegistry,
  filterWidgetKind,
  joinRelativeToken,
  listFilterValues,
  rangeFilterFor,
  type RangeOp,
  RELATIVE_PRESET_LABEL_KEYS,
  RELATIVE_PRESETS,
  type RelativePreset,
  splitRelativeToken,
  type TableLabels,
  type TableSource,
  textFilterFor,
  type TextOp,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  Directive,
  inject,
  Injector,
  input,
  type OnInit,
  type Signal,
  signal,
} from "@angular/core";

import { CHECKLIST_SLOTS } from "./checklistFilter";

/** A field's column stack: the caption is a flex item, so `gap` applies. */
const FIELD_STACK =
  "display: flex; flex-direction: column; gap: 16px; min-width: 0; margin: 0; padding: 0; border: 0";

let nextFieldId = 0;

/** A fresh id for a field's caption, which its group is labelled by. */
function fieldId(): string {
  nextFieldId += 1;
  return `adapttable-filter-${String(nextFieldId)}`;
}

/** A text filter: its operator and its value. @internal */
@Component({
  selector: "adapt-text-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ w.label }}</div>
      <div style="display: flex; flex-wrap: wrap; gap: 12px">
        <select
          data-adapttable-part="filter-operator"
          style="flex: 0 0 8.5rem; width: 8.5rem"
          [attr.aria-label]="labels().operator"
          [value]="w.op"
          (change)="pickOp($any($event.target).value)"
        >
          @for (op of w.ops; track op) {
            <option [value]="op" [selected]="op === w.op">
              {{ opLabel(w.opLabelKeys[op]) }}
            </option>
          }
        </select>
        @if (w.needsValue) {
          <input
            type="text"
            data-adapttable-part="filter-input"
            [attr.aria-label]="w.label"
            [attr.placeholder]="def().placeholder ?? null"
            [value]="w.value"
            (input)="w.write(w.op, $any($event.target).value)"
          />
        }
      </div>
    </fieldset>
  `,
})
export class AdaptTextFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly widget = textFilterFor(this.def, this.source);

  protected opLabel(key: keyof TableLabels): string {
    return filterOpLabel(this.labels(), key);
  }

  /** The select offers only the widget's operators. */
  protected pickOp(value: string): void {
    const w = this.widget();
    w.write(value as TextOp, w.value);
  }
}

/** A yes/no filter. @internal */
@Component({
  selector: "adapt-boolean-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    <label data-adapttable-part="filter-field" [style]="stack">
      <span data-adapttable-part="filter-label">{{ w.label }}</span>
      <select
        data-adapttable-part="filter-select"
        [attr.aria-label]="w.label"
        [value]="w.choice"
        (change)="pick($any($event.target).value)"
      >
        <option value="" [selected]="w.choice === ''">
          {{ labels().boolAny }}
        </option>
        <option value="true" [selected]="w.choice === 'true'">
          {{ labels().boolTrue }}
        </option>
        <option value="false" [selected]="w.choice === 'false'">
          {{ labels().boolFalse }}
        </option>
      </select>
    </label>
  `,
})
export class AdaptBooleanFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly stack = FIELD_STACK;
  protected readonly widget = booleanFilterFor(this.def, this.source);

  /** The select offers only the three choices. */
  protected pick(value: string): void {
    this.widget().write(value as "" | "true" | "false");
  }
}

/** The choices of a select or checkbox field, loaded once the field starts. */
@Directive()
abstract class OptionsField<TRow> implements OnInit {
  abstract readonly def: Signal<FilterDef<TRow>>;
  private readonly injector = inject(Injector);
  protected readonly choices = signal<Signal<FilterOptionsState> | undefined>(
    undefined
  );
  protected readonly options = computed(
    () => this.choices()?.() ?? { options: [], loading: false }
  );

  ngOnInit(): void {
    this.choices.set(filterOptionsFor(this.def(), this.injector));
  }
}

/** A single-choice filter. @internal */
@Component({
  selector: "adapt-select-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let value = current();
    <label data-adapttable-part="filter-field" [style]="stack">
      <span data-adapttable-part="filter-label">{{ caption() }}</span>
      <select
        data-adapttable-part="filter-select"
        [value]="value"
        (change)="source().setExtra(def().key, $any($event.target).value)"
      >
        @if (options().loading) {
          <option value="" disabled>…</option>
        } @else {
          <option value="" [selected]="value === ''">
            {{ labels().filterAll }}
          </option>
          @for (option of options().options; track option.value) {
            <option [value]="option.value" [selected]="option.value === value">
              {{ option.label }}
            </option>
          }
        }
      </select>
    </label>
  `,
})
export class AdaptSelectFilterField<TRow> extends OptionsField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels: the option for every value. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly stack = FIELD_STACK;
  protected readonly caption = computed(() => filterLabel(this.def()));
  protected readonly current = computed(() =>
    String(this.source().extra[this.def().key] ?? "")
  );
}

/** A multi-choice filter drawn as checkboxes. @internal */
@Component({
  selector: "adapt-multi-select-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ caption() }}</div>
      <div
        data-adapttable-part="filter-checkbox-group"
        style="display: flex; flex-wrap: wrap; gap: 10px; overflow: auto"
        [style.max-height.px]="listHeight"
      >
        @if (options().loading) {
          <span data-adapttable-part="filter-options-loading">…</span>
        } @else {
          @for (option of options().options; track option.value) {
            <label data-adapttable-part="filter-checkbox">
              <input
                type="checkbox"
                [checked]="selected().includes(option.value)"
                (change)="toggle(option.value, $any($event.target).checked)"
              />
              {{ option.label }}
            </label>
          }
        }
      </div>
    </fieldset>
  `,
})
export class AdaptMultiSelectFilterField<TRow> extends OptionsField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly listHeight = 220;
  protected readonly caption = computed(() => filterLabel(this.def()));
  protected readonly selected = computed(() =>
    listFilterValues(this.source().extra[this.def().key])
  );

  protected toggle(value: string, on: boolean): void {
    const current = this.selected();
    this.source().setExtra(
      this.def().key,
      on ? [...current, value] : current.filter((item) => item !== value)
    );
  }
}

/** An operator-first number or date range. @internal */
@Component({
  selector: "adapt-range-filter-field",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let w = widget();
    @let l = labels();
    <fieldset
      data-adapttable-part="filter-field"
      [attr.aria-labelledby]="id"
      [style]="stack"
    >
      <div data-adapttable-part="filter-label" [id]="id">{{ w.label }}</div>
      <div style="display: flex; flex-wrap: wrap; gap: 12px">
        <select
          data-adapttable-part="filter-operator"
          style="flex: 0 0 8.5rem; width: 8.5rem"
          [attr.aria-label]="l.operator"
          [value]="w.op ?? ''"
          (change)="pickOp($any($event.target).value)"
        >
          <option value="" [selected]="w.op === undefined">
            {{ l.operator }}
          </option>
          @for (op of w.ops; track op) {
            <option [value]="op" [selected]="op === w.op">
              {{ opLabel(op) }}
            </option>
          }
        </select>
        @if (w.arity === "two") {
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.from"
            [attr.aria-label]="l.from"
            [value]="w.a"
            (input)="w.write(w.op, $any($event.target).value, w.b)"
          />
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.to"
            [attr.aria-label]="l.to"
            [value]="w.b"
            (input)="w.write(w.op, w.a, $any($event.target).value)"
          />
        }
        @if (w.op === "relative") {
          @let token = relative();
          <select
            data-adapttable-part="filter-input"
            style="flex: 1 1 8.5rem; min-width: 8.5rem"
            [attr.aria-label]="l.opRelative"
            [value]="token.preset"
            (change)="pickPreset($any($event.target).value)"
          >
            @for (preset of presets; track preset) {
              <option [value]="preset" [selected]="preset === token.preset">
                {{ presetLabel(preset) }}
              </option>
            }
          </select>
          @if (token.preset === "last" || token.preset === "next") {
            <input
              type="number"
              min="1"
              data-adapttable-part="filter-input"
              style="flex: 0 0 4.5rem; width: 4.5rem"
              [attr.aria-label]="l.value"
              [value]="token.n"
              (input)="pickCount($any($event.target).value)"
            />
          }
        }
        @if (
          w.op !== undefined &&
          w.op !== "relative" &&
          w.arity !== "none" &&
          w.arity !== "two"
        ) {
          <input
            data-adapttable-part="filter-input"
            style="flex: 1 1 7rem; min-width: 7rem"
            [type]="w.inputType"
            [attr.placeholder]="l.value"
            [attr.aria-label]="l.value"
            [value]="w.a"
            (input)="w.write(w.op, $any($event.target).value, '')"
          />
        }
      </div>
    </fieldset>
  `,
})
export class AdaptRangeFilterField<TRow> {
  /** The definition. */
  readonly def = input.required<FilterDef<TRow>>();
  /** The source whose filter bag the field writes. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();

  protected readonly id = fieldId();
  protected readonly stack = FIELD_STACK;
  protected readonly presets = RELATIVE_PRESETS;
  protected readonly widget = rangeFilterFor(this.def, this.source);
  protected readonly relative = computed(() =>
    splitRelativeToken(this.widget().a)
  );

  protected opLabel(op: RangeOp): string {
    const keys = this.widget().opLabelKeys as Partial<
      Record<RangeOp, keyof TableLabels>
    >;
    const key = keys[op];
    return key ? filterOpLabel(this.labels(), key) : op;
  }

  protected presetLabel(preset: RelativePreset): string {
    return this.labels()[RELATIVE_PRESET_LABEL_KEYS[preset]];
  }

  protected pickOp(value: string): void {
    const w = this.widget();
    const next = w.ops.find((op) => op === value);
    w.setOp(next);
    w.write(next, w.a, w.b);
  }

  /** The select offers only the presets. */
  protected pickPreset(value: string): void {
    const w = this.widget();
    w.write(
      w.op,
      joinRelativeToken(value as RelativePreset, this.relative().n),
      ""
    );
  }

  protected pickCount(value: string): void {
    const w = this.widget();
    w.write(w.op, joinRelativeToken(this.relative().preset, Number(value)), "");
  }
}

/**
 * The auto-built filter form: one native field per definition.
 *
 * @public
 */
@Component({
  selector: "adapt-auto-filter-form",
  imports: [
    AdaptBooleanFilterField,
    AdaptChecklistChrome,
    AdaptMultiSelectFilterField,
    AdaptRangeFilterField,
    AdaptSelectFilterField,
    AdaptTextFilterField,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @for (def of defs(); track def.key) {
      @switch (kindOf(def)) {
        @case ("text") {
          <adapt-text-filter-field
            [def]="def"
            [source]="source()"
            [labels]="labels()"
          />
        }
        @case ("boolean") {
          <adapt-boolean-filter-field
            [def]="def"
            [source]="source()"
            [labels]="labels()"
          />
        }
        @case ("select") {
          <adapt-select-filter-field
            [def]="def"
            [source]="source()"
            [labels]="labels()"
          />
        }
        @case ("multiSelect") {
          <adapt-multi-select-filter-field [def]="def" [source]="source()" />
        }
        @case ("checklist") {
          <adapt-checklist-chrome
            [def]="def"
            [source]="source()"
            [labels]="labels()"
            [slots]="checklistSlots"
          />
        }
        @case ("range") {
          <adapt-range-filter-field
            [def]="def"
            [source]="source()"
            [labels]="labels()"
          />
        }
      }
    }
  `,
})
export class AdaptAutoFilterForm<TRow> {
  /** The resolved definitions, in order. */
  readonly defs = input.required<readonly FilterDef<TRow>[]>();
  /** The source whose filter bag the fields read and write. */
  readonly source = input.required<TableSource<TRow>>();
  /** Resolved labels. */
  readonly labels = input.required<Required<TableLabels>>();
  /** The filter type registry. */
  readonly registry = input<FilterTypeRegistry>(defaultFilterRegistry);

  protected readonly checklistSlots = CHECKLIST_SLOTS;

  /** Which field draws a definition. */
  protected kindOf(def: FilterDef<TRow>): string {
    const registry = this.registry();
    const kind: string =
      registry.get(def.type)?.widget ?? filterWidgetKind(def, registry) ?? "";
    return kind === "dateRange" || kind === "numberRange" ? "range" : kind;
  }
}

// packages/react/adapter-base-ui/src/components/AutoFilterForm.tsx
import {
  CHECKLIST_LIST_HEIGHT,
  filterOpLabel,
  listFilterValues,
  scalarFilterText,
  useBooleanFilterWidget,
  useFilterOptions,
  useRangeFilterWidget,
  useTextFilterWidget,
} from "@adapttable/react";
import {
  defaultFilterRegistry,
  type Direction,
  type FilterDef,
  type FilterFormSource,
  filterLabel,
  type FilterTypeRegistry,
  filterWidgetKind,
  joinRelativeToken,
  RELATIVE_PRESET_LABEL_KEYS,
  RELATIVE_PRESETS,
  renderRegisteredFilter,
  resolveLabels,
  splitRelativeToken,
  type TableLabels,
} from "@adapttable/react/adapter";
import { type ReactElement, type ReactNode, useId } from "react";

import type { BaseUiAccentColor } from "../types";
import { Flex, Spinner, Text, TextField } from "../ui";
import { ChecklistFilter } from "./ChecklistFilter";
import {
  Checkbox,
  FormField,
  NativeSelect,
  type SelectOption,
} from "./primitives";

/**
 * A labelled GROUP wrapper for multi-control fields (the multiSelect chip
 * group). Unlike `FormField` the label carries an `id` so the group
 * references it via `aria-labelledby` instead of naming a single control.
 */
function GroupField({
  label,
  id,
  children,
}: Readonly<{ label: ReactNode; id: string; children: ReactNode }>) {
  return (
    <Flex direction="column" gap="4">
      <Text id={id} as="span" size="2">
        {label}
      </Text>
      {children}
    </Flex>
  );
}

/** Props for `AutoFilterForm`. */
export interface AutoFilterFormProps<TRow> {
  /** Writing direction (kept for parity; Base UI controls flip from ambient dir). */
  dir?: Direction;
  /** The resolved filter definitions, in render order. */
  defs: readonly FilterDef<TRow>[];
  /** The resolved table source (filter bag + setters). */
  source: FilterFormSource<TRow>;
  /** Base UI accent color for option checkboxes. */
  accentColor?: BaseUiAccentColor;
  /** Pre-translated label overrides (operator names, From/To, …). */
  labels?: TableLabels;
  /** Type registry; defaults to the built-ins. */
  registry?: FilterTypeRegistry;
}

/** Preset select + optional N for last/next. Stores the token. */
function RelativeTokenField({
  labels,
  value,
  onValue,
}: Readonly<{
  labels: Required<TableLabels>;
  value: string;
  onValue: (next: string) => void;
}>) {
  const { preset, n } = splitRelativeToken(value);
  const counted = preset === "last" || preset === "next";
  return (
    <>
      <NativeSelect
        size="1"
        width="8.5rem"
        aria-label={labels.opRelative}
        value={preset}
        options={RELATIVE_PRESETS.map((p) => ({
          value: p,
          label: labels[RELATIVE_PRESET_LABEL_KEYS[p]],
        }))}
        onValueChange={(next) => {
          const found = RELATIVE_PRESETS.find((p) => p === next);
          if (found) onValue(joinRelativeToken(found, n));
        }}
      />
      {counted && (
        <TextField.Root
          size="1"
          type="number"
          min={1}
          aria-label={labels.value}
          value={String(n)}
          onChange={(e) =>
            onValue(joinRelativeToken(preset, Number(e.target.value)))
          }
          style={{ flex: "0 0 4.5rem", width: "4.5rem" }}
        />
      )}
    </>
  );
}

/**
 * Operator-first range widget (`numberRange` / `dateRange`): a comparison
 * select, then ONE bound input — or a From/To pair for "Between". The widget
 * logic (operator seeding, bound derivation, writes) lives in core's
 * `useRangeFilterWidget`; this renders the Base UI controls over it.
 */
function RangeField<TRow>({
  def,
  source,
  labels,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
}>) {
  const id = useId();
  const { label, ops, opLabelKeys, inputType, arity, op, setOp, a, b, write } =
    useRangeFilterWidget(def, source);
  // The operator select offers a "no comparison" clear choice (empty value)
  // followed by every range operator.
  const opOptions: SelectOption[] = [
    { value: "", label: labels.operator },
    ...ops.map((o) => ({
      value: o,
      label: filterOpLabel(labels, opLabelKeys[o as keyof typeof opLabelKeys]),
    })),
  ];
  return (
    <FormField label={label}>
      {/* Operator and value(s) share ONE row — it reads like a sentence:
          "At least [5]". */}
      <Flex gap="2" align="start" wrap="wrap">
        <NativeSelect
          size="1"
          width="8.5rem"
          aria-label={labels.operator}
          data-adapttable-part="filter-operator"
          placeholder={labels.operator}
          value={op ?? ""}
          options={opOptions}
          onValueChange={(value) => {
            const next = ops.find((o) => o === value);
            setOp(next);
            write(next, a, b);
          }}
        />
        {arity === "two" && (
          <>
            <TextField.Root
              id={`${id}-a`}
              size="1"
              type={inputType}
              aria-label={labels.from}
              placeholder={labels.from}
              value={a}
              onChange={(e) => write(op, e.target.value, b)}
              style={{ flex: "1 1 7rem", minWidth: "7rem" }}
            />
            <TextField.Root
              id={`${id}-b`}
              size="1"
              type={inputType}
              aria-label={labels.to}
              placeholder={labels.to}
              value={b}
              onChange={(e) => write(op, a, e.target.value)}
              style={{ flex: "1 1 7rem", minWidth: "7rem" }}
            />
          </>
        )}
        {op === "relative" && (
          <RelativeTokenField
            labels={labels}
            value={a}
            onValue={(next) => write(op, next, "")}
          />
        )}
        {op !== undefined &&
          op !== "relative" &&
          arity !== "none" &&
          arity !== "two" && (
            <TextField.Root
              id={`${id}-a`}
              size="1"
              type={inputType}
              aria-label={labels.value}
              placeholder={labels.value}
              value={a}
              onChange={(e) => write(op, e.target.value, "")}
              style={{ flex: "1 1 7rem", minWidth: "7rem" }}
            />
          )}
      </Flex>
    </FormField>
  );
}

/** Operator-first text filter: comparison select, then the term (if needed). */
function TextFilterField<TRow>({
  def,
  source,
  labels,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
}>) {
  const { label, ops, opLabelKeys, op, value, needsValue, write } =
    useTextFilterWidget(def, source);
  const opOptions: SelectOption[] = ops.map((choice) => ({
    value: choice,
    label: filterOpLabel(labels, opLabelKeys[choice]),
  }));
  return (
    <FormField label={label}>
      <Flex gap="2" align="start" wrap="wrap">
        <NativeSelect
          size="1"
          width="8.5rem"
          aria-label={labels.operator}
          data-adapttable-part="filter-operator"
          value={op}
          options={opOptions}
          onValueChange={(next) => {
            const found = ops.find((choice) => choice === next);
            if (found) write(found, value);
          }}
        />
        {needsValue && (
          <TextField.Root
            size="1"
            aria-label={label}
            data-adapttable-part="filter-input"
            value={value}
            placeholder={def.placeholder}
            onChange={(e) => write(op, e.target.value)}
            style={{ flex: "1 1 7rem", minWidth: "7rem" }}
          />
        )}
      </Flex>
    </FormField>
  );
}

function BooleanFilterField<TRow>({
  def,
  source,
  labels,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
}>) {
  const { label, choice, write } = useBooleanFilterWidget(def, source);
  return (
    <FormField label={label}>
      <NativeSelect
        size="1"
        aria-label={label}
        data-adapttable-part="filter-select"
        value={choice}
        options={[
          { value: "", label: labels.boolAny },
          { value: "true", label: labels.boolTrue },
          { value: "false", label: labels.boolFalse },
        ]}
        onValueChange={(next) => {
          if (next === "" || next === "true" || next === "false") write(next);
        }}
      />
    </FormField>
  );
}

/** One definition rendered as its kit-native Base UI control. */
function AutoFilterField<TRow>({
  def,
  source,
  labels,
  accentColor,
  registry,
}: Readonly<{
  def: FilterDef<TRow>;
  source: FilterFormSource<TRow>;
  labels: Required<TableLabels>;
  accentColor?: BaseUiAccentColor;
  registry: FilterTypeRegistry;
}>): ReactElement | null {
  const id = useId();
  const { extra, setExtra } = source;
  const label = filterLabel(def);
  // Static arrays resolve instantly; async loaders run once and report
  // `loading` so the select/checkbox controls can show a native affordance.
  const { options, loading } = useFilterOptions(def);
  const custom = renderRegisteredFilter(def, source, labels, registry);
  if (custom) return custom as ReactElement;
  switch (filterWidgetKind(def, registry)) {
    case "text":
      return <TextFilterField def={def} source={source} labels={labels} />;
    case "boolean":
      return <BooleanFilterField def={def} source={source} labels={labels} />;
    case "select": {
      const selectOptions: SelectOption[] = loading
        ? [{ value: "", label: "…", disabled: true }]
        : [
            { value: "", label: labels.filterAll },
            ...options.map((option) => ({
              value: option.value,
              label: option.label,
            })),
          ];
      return (
        <FormField label={label}>
          <NativeSelect
            size="1"
            aria-label={label}
            value={scalarFilterText(extra[def.key])}
            options={selectOptions}
            onValueChange={(value) => setExtra(def.key, value)}
          />
        </FormField>
      );
    }
    case "checklist":
      return <ChecklistFilter def={def} source={source} labels={labels} />;
    case "multiSelect": {
      const selected = listFilterValues(extra[def.key]);
      const toggle = (value: string) =>
        setExtra(
          def.key,
          selected.includes(value)
            ? selected.filter((v) => v !== value)
            : [...selected, value]
        );
      return (
        <GroupField label={label} id={id}>
          {loading ? (
            <Spinner size="1" label={labels.loading} />
          ) : (
            <Flex
              gap="2"
              wrap="wrap"
              role="group"
              aria-labelledby={id}
              style={{
                maxHeight: CHECKLIST_LIST_HEIGHT,
                overflow: "auto",
              }}
            >
              {options.map((option) => {
                const checked = selected.includes(option.value);
                return (
                  <label
                    key={option.value}
                    className="adapttable-filter-chip"
                    data-checked={checked ? "true" : "false"}
                    data-accent={accentColor}
                  >
                    <Checkbox
                      checked={checked}
                      color={accentColor}
                      value={option.value}
                      className="adapttable-visually-hidden"
                      onToggle={() => toggle(option.value)}
                    />
                    {option.label}
                  </label>
                );
              })}
            </Flex>
          )}
        </GroupField>
      );
    }
    case "dateRange":
    case "numberRange":
      return <RangeField def={def} source={source} labels={labels} />;
    default:
      return null;
  }
}

/**
 * The auto-built filter form: one kit-native Base UI control per
 * declarative `FilterDef`, reading and writing the source's extra-filter
 * bag — `""` / `[]` clears a key. Rendered inside the filter popover or dialog
 * when the `filters` prop is the declarative array form.
 *
 * @typeParam TRow - The row type.
 */
export function AutoFilterForm<TRow>({
  defs,
  source,
  accentColor,
  labels,
  registry = defaultFilterRegistry,
}: Readonly<AutoFilterFormProps<TRow>>) {
  const resolved = resolveLabels(labels);
  return (
    <Flex direction="column" gap="5">
      {defs.map((def) => (
        <AutoFilterField
          key={def.key}
          def={def}
          source={source}
          labels={resolved}
          accentColor={accentColor}
          registry={registry}
        />
      ))}
    </Flex>
  );
}
