// packages/react/adapter-base-ui/src/components/GroupingPanel.tsx
/** The interactive row-grouping panel, in Base UI. */
import {
  GripIcon,
  type GroupingPanelAggregationItemProps,
  type GroupingPanelAggregationRemoveProps,
  type GroupingPanelChecklistProps,
  type GroupingPanelChipProps,
  GroupingPanelChrome,
  type GroupingPanelChromeProps,
  type GroupingPanelDropZoneProps,
  type GroupingPanelRemoveZoneProps,
  type GroupingPanelRestoreProps,
  type GroupingPanelSelectProps,
  type GroupingPanelSlots,
  type GroupingPanelSurfaceProps,
} from "@adapttable/react/adapter";

import { ensureBaseUiGroupingStyles } from "../injectStyles";
import { Button, IconButton, Text } from "../ui";
import { NativeSelect } from "./primitives";

/** Closed add control: the shown placeholder plus the kit chevron. */
function addControlWidth(label: string): string {
  return `calc(${Math.max(label.length, 1)}ch + 2.75rem)`;
}

const slots: GroupingPanelSlots = {
  Surface: ({
    children,
    label,
    mobile,
    ...rest
  }: GroupingPanelSurfaceProps) => (
    <section
      aria-label={label}
      className="adapttable-grouping-panel"
      data-mobile={mobile ? true : undefined}
      {...rest}
    >
      {children}
    </section>
  ),
  DropZone: ({
    label,
    empty,
    active,
    dragging,
    dropProps,
    ...rest
  }: GroupingPanelDropZoneProps) => (
    <fieldset
      aria-label={label}
      className="adapttable-grouping-drop-zone"
      data-empty={empty ? true : undefined}
      data-active={active ? true : undefined}
      data-dragging={dragging ? true : undefined}
      {...dropProps}
      {...rest}
    >
      {empty ? label : <span aria-hidden="true" />}
    </fieldset>
  ),
  Chip: ({
    label,
    level,
    dragProps,
    keyboardProps,
    onRemove,
    removeLabel,
    ...rest
  }: GroupingPanelChipProps) => (
    <span className="adapttable-grouping-chip" data-level={level} {...rest}>
      <Button
        type="button"
        size="1"
        variant="ghost"
        data-adapttable-part="grouping-chip-handle"
        className="adapttable-grouping-chip__handle"
        {...dragProps}
        {...keyboardProps}
      >
        <GripIcon />
        <span>{label}</span>
      </Button>
      <IconButton
        type="button"
        size="1"
        variant="ghost"
        color="gray"
        data-adapttable-part="grouping-chip-remove"
        aria-label={removeLabel}
        className="adapttable-grouping-chip__remove"
        data-no-group-drag=""
        onClick={onRemove}
      >
        {"\u00d7"}
      </IconButton>
    </span>
  ),
  Select: ({
    label,
    value,
    options,
    onChange,
    disabled,
    ...rest
  }: GroupingPanelSelectProps) => (
    <NativeSelect
      size="1"
      aria-label={label}
      value={value}
      placeholder={label}
      disabled={disabled}
      options={options}
      onValueChange={onChange}
      {...rest}
      width={
        rest["data-adapttable-part"] === "grouping-add"
          ? addControlWidth(label)
          : undefined
      }
    />
  ),
  RemoveZone: ({
    label,
    active,
    dropProps,
    ...rest
  }: GroupingPanelRemoveZoneProps) => (
    <fieldset
      aria-label={label}
      className="adapttable-grouping-remove-zone"
      data-active={active ? true : undefined}
      {...dropProps}
      {...rest}
    >
      {label}
    </fieldset>
  ),
  AggregationItem: ({
    label,
    readOnly,
    readOnlyLabel,
    children,
    ...rest
  }: GroupingPanelAggregationItemProps) => (
    <span
      className="adapttable-grouping-aggregation-item"
      data-read-only={readOnly || undefined}
      {...rest}
    >
      <Text>{label}</Text>
      {readOnly ? <Text>{readOnlyLabel}</Text> : children}
    </span>
  ),
  AggregationRemove: ({
    label,
    onRemove,
    ...rest
  }: GroupingPanelAggregationRemoveProps) => (
    <IconButton aria-label={label} onClick={onRemove} {...rest}>
      {"\u00d7"}
    </IconButton>
  ),
  AggregationPicker: ({
    label,
    options,
    onToggle,
    disabled,
    ...rest
  }: GroupingPanelChecklistProps) => {
    const available = options.filter((option) => !option.checked);
    return (
      <NativeSelect
        size="1"
        aria-label={label}
        value=""
        placeholder={label}
        disabled={disabled === true || available.length === 0}
        options={available}
        onValueChange={(value) => {
          if (value) onToggle(value, true);
        }}
        className="adapttable-btn"
        {...rest}
        width={addControlWidth(label)}
      />
    );
  },
  AggregationRestore: ({
    label,
    disabled,
    onRestore,
    ...rest
  }: GroupingPanelRestoreProps) => (
    <Button variant="outline" disabled={disabled} onClick={onRestore} {...rest}>
      {label}
    </Button>
  ),
};

/**
 * Configure row grouping by adding, reordering, and removing columns.
 *
 * @public
 */
export function GroupingPanel<TRow>(
  props: Readonly<Omit<GroupingPanelChromeProps<TRow>, "slots">>
) {
  ensureBaseUiGroupingStyles();
  return <GroupingPanelChrome {...props} slots={slots} />;
}

// packages/angular/adapter-angular-unstyled/src/groupingPanel.ts
/**
 * The grouping strip in native HTML: the binding's Chrome, filled with the
 * browser's own controls.
 */
import {
  AdaptGroupingPanelChrome,
  type AngularGroupingPanelAggregationItemProps,
  type AngularGroupingPanelSurfaceProps,
  type ColumnDef,
  type GroupingPanelAggregationRemoveProps,
  type GroupingPanelChecklistProps,
  type GroupingPanelChipProps,
  type GroupingPanelDropZoneProps,
  type GroupingPanelRemoveZoneProps,
  type GroupingPanelRestoreProps,
  type GroupingPanelSelectProps,
  type GroupingPanelSlotProps,
  type GroupingPanelSlots,
} from "@adapttable/angular";
import { NgTemplateOutlet } from "@angular/common";
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

/** Closed add control: the shown placeholder plus the native chevron. */
function addControlWidth(label: string): string {
  return `calc(${String(label.length)}ch + 2.75rem)`;
}

@Component({
  selector: "adapt-grouping-surface",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <section
      [attr.aria-label]="p.label"
      [attr.data-mobile]="p.mobile ? true : null"
      [attr.dir]="p.dir ?? null"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      style="display: flex; flex-wrap: wrap; align-items: center; gap: 8px"
      (dragenter)="p.onDragEnter?.($event)"
      (dragover)="p.onDragOver?.($event)"
      (dragleave)="p.onDragLeave?.($event)"
      (drop)="p.onDrop?.($event)"
    >
      <ng-container [ngTemplateOutlet]="p.children" />
    </section>
  `,
})
class AdaptGroupingSurface {
  readonly props = input.required<AngularGroupingPanelSurfaceProps>();
}

@Component({
  selector: "adapt-grouping-drop-zone",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <fieldset
      [attr.aria-label]="p.label"
      [attr.data-empty]="p.empty ? true : null"
      [attr.data-active]="p.active ? true : null"
      [attr.data-dragging]="p.dragging ? true : null"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      [attr.data-drop-active]="p.dropProps['data-drop-active'] ? true : null"
      (dragenter)="p.dropProps.onDragEnter?.($event)"
      (dragover)="p.dropProps.onDragOver?.($event)"
      (dragleave)="p.dropProps.onDragLeave?.($event)"
      (drop)="p.dropProps.onDrop?.($event)"
    >
      @if (p.empty) {
        {{ p.label }}
      } @else {
        <span aria-hidden="true">│</span>
      }
    </fieldset>
  `,
})
class AdaptGroupingDropZone {
  readonly props = input.required<GroupingPanelDropZoneProps<DragEvent>>();
}

@Component({
  selector: "adapt-grouping-chip",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <span
      [attr.data-level]="p.level"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      style="display: inline-flex; align-items: center; gap: 4px"
    >
      <button
        type="button"
        data-adapttable-part="grouping-chip-handle"
        [attr.draggable]="p.dragProps.draggable ? 'true' : null"
        [attr.data-grouping-dragging]="
          p.dragProps['data-grouping-dragging'] ? true : null
        "
        [attr.tabindex]="p.keyboardProps.tabIndex"
        [attr.role]="p.keyboardProps.role"
        [attr.aria-label]="p.keyboardProps['aria-label']"
        (dragstart)="p.dragProps.onDragStart?.($event)"
        (dragend)="p.dragProps.onDragEnd?.($event)"
        (keydown)="p.keyboardProps.onKeyDown($event)"
      >
        <span aria-hidden="true">⋮⋮</span> {{ p.label }}
      </button>
      <button
        type="button"
        [attr.aria-label]="p.removeLabel"
        data-adapttable-part="grouping-chip-remove"
        (click)="p.onRemove()"
      >
        <span aria-hidden="true">✕</span>
      </button>
    </span>
  `,
})
class AdaptGroupingChip {
  readonly props =
    input.required<GroupingPanelChipProps<KeyboardEvent, DragEvent>>();
}

@Component({
  selector: "adapt-grouping-select",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <select
      [attr.aria-label]="p.label"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      [disabled]="p.disabled ?? false"
      [value]="p.value"
      [style.width]="
        p['data-adapttable-part'] === 'grouping-add' ? width(p.label) : null
      "
      (change)="p.onChange($any($event.target).value)"
    >
      @if (p["data-adapttable-part"] === "grouping-add") {
        <option value="" disabled hidden>{{ p.label }}</option>
      }
      @for (option of p.options; track option.value) {
        <option [value]="option.value">{{ option.label }}</option>
      }
    </select>
  `,
})
class AdaptGroupingSelect {
  readonly props = input.required<GroupingPanelSelectProps>();
  protected readonly width = addControlWidth;
}

@Component({
  selector: "adapt-grouping-remove-zone",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <fieldset
      [attr.aria-label]="p.label"
      [attr.data-active]="p.active ? true : null"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      (dragenter)="p.dropProps.onDragEnter?.($event)"
      (dragover)="p.dropProps.onDragOver?.($event)"
      (dragleave)="p.dropProps.onDragLeave?.($event)"
      (drop)="p.dropProps.onDrop?.($event)"
    >
      {{ p.label }}
    </fieldset>
  `,
})
class AdaptGroupingRemoveZone {
  readonly props = input.required<GroupingPanelRemoveZoneProps<DragEvent>>();
}

@Component({
  selector: "adapt-grouping-aggregation-item",
  imports: [NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <span
      [attr.data-read-only]="p.readOnly ? true : null"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
    >
      <span>{{ p.label }}</span>
      @if (p.readOnly) {
        <span>{{ p.readOnlyLabel }}</span>
      } @else {
        <ng-container [ngTemplateOutlet]="p.children" />
      }
    </span>
  `,
})
class AdaptGroupingAggregationItem {
  readonly props = input.required<AngularGroupingPanelAggregationItemProps>();
}

@Component({
  selector: "adapt-grouping-aggregation-remove",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <button
      type="button"
      [attr.aria-label]="p.label"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      (click)="p.onRemove()"
    >
      ×
    </button>
  `,
})
class AdaptGroupingAggregationRemove {
  readonly props = input.required<GroupingPanelAggregationRemoveProps>();
}

@Component({
  selector: "adapt-grouping-aggregation-picker",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <select
      [attr.aria-label]="p.label"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      [disabled]="p.disabled === true || available().length === 0"
      [style.width]="width(p.label)"
      (change)="choose($any($event.target))"
    >
      <option value="" disabled hidden>{{ p.label }}</option>
      @for (option of available(); track option.value) {
        <option
          [value]="option.value"
          data-adapttable-part="grouping-aggregation-option"
        >
          {{ option.label }}
        </option>
      }
    </select>
  `,
})
class AdaptGroupingAggregationPicker {
  readonly props = input.required<GroupingPanelChecklistProps>();
  protected readonly width = addControlWidth;
  protected readonly available = () =>
    this.props().options.filter((option) => !option.checked);

  protected choose(select: HTMLSelectElement): void {
    if (select.value === "") return;
    this.props().onToggle(select.value, true);
    select.value = "";
  }
}

@Component({
  selector: "adapt-grouping-aggregation-restore",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <button
      type="button"
      [disabled]="p.disabled"
      [attr.data-adapttable-part]="p['data-adapttable-part']"
      (click)="p.onRestore()"
    >
      {{ p.label }}
    </button>
  `,
})
class AdaptGroupingAggregationRestore {
  readonly props = input.required<GroupingPanelRestoreProps>();
}

const SLOTS: GroupingPanelSlots = {
  Surface: AdaptGroupingSurface,
  DropZone: AdaptGroupingDropZone,
  Chip: AdaptGroupingChip,
  Select: AdaptGroupingSelect,
  RemoveZone: AdaptGroupingRemoveZone,
  AggregationItem: AdaptGroupingAggregationItem,
  AggregationRemove: AdaptGroupingAggregationRemove,
  AggregationPicker: AdaptGroupingAggregationPicker,
  AggregationRestore: AdaptGroupingAggregationRestore,
};

/**
 * The grouping strip drawn with native controls. A slot fill receives the
 * panel's props through one `props` input.
 *
 * @public
 */
@Component({
  selector: "adapt-grouping-panel",
  imports: [AdaptGroupingPanelChrome],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let p = props();
    <adapt-grouping-panel-chrome
      [state]="p.state"
      [columns]="p.columns"
      [labels]="p.labels"
      [mobile]="p.mobile"
      [dir]="p.dir"
      [slots]="slots"
    />
  `,
})
export class AdaptGroupingPanel<TRow> {
  /** The strip's state and columns, from the table's grouping feature. */
  readonly props = input.required<GroupingPanelSlotProps<ColumnDef<TRow>>>();

  protected readonly slots = SLOTS;
}
