// packages/react/react/src/filters/FilterTreeChrome.tsx
/**
 * AND/OR filter-tree layout. Structure only — adapters pass the Select,
 * Input and Button the end user clicks. Core does not draw form controls.
 */
import {
  defaultFilterRegistry,
  type FilterDef,
  filterTreeCombinatorOptions,
  type FilterTreeConditionModel,
  filterTreeConditionModel,
  filterTreeEditorActions,
  type FilterTreeOption,
  type FilterTypeRegistry,
  isFilterGroup,
  type QueryCondition,
  type QueryFilterGroup,
  resolveLabels,
  type TableLabels,
  type TableSource,
} from "@adapttable/core";
import { type CSSProperties, type ReactNode, useState } from "react";

export type { FilterTreeOption } from "@adapttable/core";

/**
 * Class hooks the unstyled adapter maps onto `DataTableClassNames`.
 *
 * @public
 */
export interface FilterTreeClassNames {
  /** Class for the whole builder. */
  filterTree?: string;
  /** Class for an AND/OR group. */
  filterTreeGroup?: string;
  /** Class for one condition row. */
  filterTreeCondition?: string;
  /** Class for a group's action bar. */
  filterTreeActions?: string;
  /** Class for a remove button. */
  filterTreeRemove?: string;
  /** Class for the disclosure summary. */
  filterTreeSummary?: string;
  /** Class for the simple filter form. */
  filtersForm?: string;
  /** Class for one field wrapper. */
  filterField?: string;
  /** Class for a field's label. */
  filterLabel?: string;
  /** Class for a text input. */
  filterInput?: string;
  /** Class for a select. */
  filterSelect?: string;
  /** Class for the operator select. */
  filterOperator?: string;
}

/**
 * Props for an adapter `FilterTreeBuilder` — no slots on the public API.
 *
 * @public
 */
export interface FilterTreeBuilderProps<TRow> {
  /** Filter definitions the builder can offer. */
  readonly defs: readonly FilterDef<TRow>[];
  /** Reads and writes the filter tree. */
  readonly source: Pick<TableSource<TRow>, "filterTree" | "setFilterTree">;
  /** Label overrides; gaps fall back to English. */
  readonly labels?: TableLabels;
  /** Per-part classes. */
  readonly classNames?: FilterTreeClassNames;
  /** Custom filter types, beyond the built-ins. */
  readonly registry?: FilterTypeRegistry;
  /** Open Advanced on first paint. Default: open only when a tree already exists. */
  readonly defaultExpanded?: boolean;
}

/**
 * Kit Select the tree layout calls.
 *
 * @public
 */
export interface FilterTreeSelectProps {
  /** Accessible name for the select. */
  readonly label: string;
  /** Currently chosen value. */
  readonly value: string;
  /** Part name for the control, so styling can target it. */
  readonly part: string;
  /** Choices to offer. */
  readonly options: readonly FilterTreeOption[];
  /** Class for the select. */
  readonly className?: string;
  /** Class for the field wrapper. */
  readonly fieldClassName?: string;
  /** Class for the label. */
  readonly labelClassName?: string;
  /** Called with the chosen value. */
  readonly onChange: (value: string) => void;
}

/**
 * Kit text/number/date field the tree layout calls.
 *
 * @public
 */
export interface FilterTreeInputProps {
  /** Accessible name for the field. */
  readonly label: string;
  /** Current text. */
  readonly value: string;
  /** Which input type the value is edited with. */
  readonly type: "text" | "number" | "date";
  /** Class for the input. */
  readonly className?: string;
  /** Class for the field wrapper. */
  readonly fieldClassName?: string;
  /** Class for the label. */
  readonly labelClassName?: string;
  /** Called with the new text. */
  readonly onChange: (value: string) => void;
}

/**
 * Kit button the tree layout calls.
 *
 * @public
 */
export interface FilterTreeButtonProps {
  /** Caption and accessible name. */
  readonly label: string;
  /** Part name for the button, so styling can target it. */
  readonly part?: string;
  /** Class for the button. */
  readonly className?: string;
  /** Called when pressed. */
  readonly onClick: () => void;
}

/**
 * Kit disclosure that owns the Advanced section's visible chrome.
 *
 * @public
 */
export interface FilterTreeDisclosureProps {
  /** Caption on the summary. */
  readonly label: string;
  /** Whether the section is open. */
  readonly expanded: boolean;
  /** Class for the disclosure. */
  readonly className?: string;
  /** Class for the summary. */
  readonly summaryClassName?: string;
  /** Content revealed when open. */
  readonly children: ReactNode;
  /** Called with the new open state. */
  readonly onExpandedChange: (expanded: boolean) => void;
}

/**
 * Adapter-supplied controls for {@link FilterTreeChrome}.
 *
 * @public
 */
export interface FilterTreeSlots {
  /** Renders a choice control. */
  readonly Select: (props: FilterTreeSelectProps) => ReactNode;
  /** Renders a text, number or date field. */
  readonly Input: (props: FilterTreeInputProps) => ReactNode;
  /** Renders an action button. */
  readonly Button: (props: FilterTreeButtonProps) => ReactNode;
  /** Renders the collapsible Advanced section. */
  readonly Disclosure: (props: FilterTreeDisclosureProps) => ReactNode;
}

/** One compact condition — field, operator, value, remove on a wrapping row. */
const TREE_ROW: CSSProperties = {
  display: "flex",
  flexWrap: "wrap",
  alignItems: "flex-end",
  gap: 8,
  minWidth: 0,
};

/** Nested groups and the Advanced shell stack rows, they do not list fields. */
const TREE_STACK: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 8,
  minWidth: 0,
};

const TREE_GROUP_ROOT: CSSProperties = {
  ...TREE_STACK,
  position: "relative",
  margin: 0,
  padding: 0,
  border: "none",
  minInlineSize: 0,
};

/** Nested groups sit on a rail so AND/OR depth is visible. */
const TREE_GROUP_NESTED: CSSProperties = {
  ...TREE_STACK,
  position: "relative",
  marginBlockStart: 4,
  marginInlineStart: 16,
  marginInlineEnd: 0,
  paddingBlock: 8,
  paddingInlineStart: 12,
  border: "none",
  borderInlineStart:
    "2px solid color-mix(in srgb, currentColor 22%, transparent)",
  backgroundColor: "color-mix(in srgb, currentColor 5%, transparent)",
  minInlineSize: 0,
};

const TREE_LEGEND_HIDDEN: CSSProperties = {
  position: "absolute",
  width: "1px",
  height: "1px",
  margin: "-1px",
  padding: 0,
  overflow: "hidden",
  clip: "rect(0, 0, 0, 0)",
  whiteSpace: "nowrap",
  border: 0,
};

/**
 * Props for {@link FilterTreeChrome}.
 *
 * @public
 */
export interface FilterTreeChromeProps<
  TRow,
> extends FilterTreeBuilderProps<TRow> {
  /** The kit's controls for the builder's fields and buttons. */
  readonly slots: FilterTreeSlots;
}

function ConditionValue<TRow>({
  model,
  labels,
  classNames,
  slots,
  onChange,
}: Readonly<{
  model: FilterTreeConditionModel<TRow>;
  labels: Required<TableLabels>;
  classNames: FilterTreeClassNames;
  slots: FilterTreeSlots;
  onChange: (value: unknown) => void;
}>) {
  const editor = model.value;
  const Select = slots.Select;
  const Input = slots.Input;
  switch (editor.kind) {
    case "none":
      return null;
    case "boolean":
      return (
        <Select
          label={labels.value}
          value={editor.choice}
          part="filter-select"
          className={classNames.filterSelect}
          fieldClassName={classNames.filterField}
          labelClassName={classNames.filterLabel}
          options={editor.options}
          onChange={(next) => onChange(editor.write(next))}
        />
      );
    case "relative":
      return (
        <>
          <Select
            label={labels.opRelative}
            value={editor.preset}
            part="filter-select"
            className={classNames.filterSelect}
            fieldClassName={classNames.filterField}
            labelClassName={classNames.filterLabel}
            options={editor.options}
            onChange={(next) => onChange(editor.writePreset(next))}
          />
          {editor.counted ? (
            <Input
              label="N"
              type="number"
              value={String(editor.n)}
              className={classNames.filterInput}
              fieldClassName={classNames.filterField}
              labelClassName={classNames.filterLabel}
              onChange={(next) => onChange(editor.writeCount(next))}
            />
          ) : null}
        </>
      );
    case "between":
      return (
        <>
          <Input
            label={labels.from}
            type={editor.type}
            value={editor.a}
            className={classNames.filterInput}
            fieldClassName={classNames.filterField}
            labelClassName={classNames.filterLabel}
            onChange={(next) => onChange(editor.writeA(next))}
          />
          <Input
            label={labels.to}
            type={editor.type}
            value={editor.b}
            className={classNames.filterInput}
            fieldClassName={classNames.filterField}
            labelClassName={classNames.filterLabel}
            onChange={(next) => onChange(editor.writeB(next))}
          />
        </>
      );
    case "single":
      return (
        <Input
          label={labels.value}
          type={editor.type}
          value={editor.text}
          className={classNames.filterInput}
          fieldClassName={classNames.filterField}
          labelClassName={classNames.filterLabel}
          onChange={(next) => onChange(editor.write(next))}
        />
      );
  }
}

function ConditionRow<TRow>({
  condition,
  path,
  defs,
  labels,
  classNames,
  registry,
  slots,
  onReplace,
  onRemove,
}: Readonly<{
  condition: QueryCondition;
  path: readonly number[];
  defs: readonly FilterDef<TRow>[];
  labels: Required<TableLabels>;
  classNames: FilterTreeClassNames;
  registry: FilterTypeRegistry;
  slots: FilterTreeSlots;
  onReplace: (path: readonly number[], next: QueryCondition) => void;
  onRemove: (path: readonly number[]) => void;
}>) {
  const model = filterTreeConditionModel(condition, defs, registry, labels);
  if (!model) return null;
  const Select = slots.Select;
  const Button = slots.Button;
  return (
    <div
      data-adapttable-part="filter-tree-condition"
      className={classNames.filterTreeCondition}
      style={TREE_ROW}
    >
      <Select
        label={labels.filterField}
        value={model.def.key}
        part="filter-select"
        className={classNames.filterSelect}
        fieldClassName={classNames.filterField}
        labelClassName={classNames.filterLabel}
        options={model.fieldOptions}
        onChange={(key) => {
          const next = model.withField(key);
          if (next) onReplace(path, next);
        }}
      />
      {model.opOptions.length > 0 ? (
        <Select
          label={labels.operator}
          value={condition.op}
          part="filter-operator"
          className={classNames.filterOperator}
          fieldClassName={classNames.filterField}
          labelClassName={classNames.filterLabel}
          options={model.opOptions}
          onChange={(op) => onReplace(path, model.withOp(op))}
        />
      ) : null}
      <ConditionValue
        model={model}
        labels={labels}
        classNames={classNames}
        slots={slots}
        onChange={(value) => onReplace(path, model.withValue(value))}
      />
      <Button
        label={labels.filterRemoveCondition}
        part="filter-tree-remove"
        className={classNames.filterTreeRemove}
        onClick={() => onRemove(path)}
      />
    </div>
  );
}

function GroupActions({
  labels,
  classNames,
  slots,
  onAddCondition,
  onAddGroup,
}: Readonly<{
  labels: Required<TableLabels>;
  classNames: FilterTreeClassNames;
  slots: FilterTreeSlots;
  onAddCondition: () => void;
  onAddGroup: () => void;
}>) {
  const Button = slots.Button;
  return (
    <div
      data-adapttable-part="filter-tree-actions"
      className={classNames.filterTreeActions}
      style={TREE_ROW}
    >
      <Button label={labels.filterAddCondition} onClick={onAddCondition} />
      <Button label={labels.filterAddGroup} onClick={onAddGroup} />
    </div>
  );
}

function GroupView<TRow>({
  group,
  path,
  defs,
  labels,
  classNames,
  registry,
  slots,
  onCombinator,
  onAddCondition,
  onAddGroup,
  onReplace,
  onRemove,
}: Readonly<{
  group: QueryFilterGroup;
  path: readonly number[];
  defs: readonly FilterDef<TRow>[];
  labels: Required<TableLabels>;
  classNames: FilterTreeClassNames;
  registry: FilterTypeRegistry;
  slots: FilterTreeSlots;
  onCombinator: (path: readonly number[], next: string) => void;
  onAddCondition: (path: readonly number[]) => void;
  onAddGroup: (path: readonly number[]) => void;
  onReplace: (path: readonly number[], next: QueryCondition) => void;
  onRemove: (path: readonly number[]) => void;
}>) {
  const Select = slots.Select;
  const Button = slots.Button;
  return (
    <fieldset
      data-adapttable-part="filter-tree-group"
      data-depth={path.length}
      className={classNames.filterTreeGroup}
      style={path.length > 0 ? TREE_GROUP_NESTED : TREE_GROUP_ROOT}
    >
      <legend style={TREE_LEGEND_HIDDEN}>
        {group.combinator === "or"
          ? labels.filterCombinatorOr
          : labels.filterCombinatorAnd}
      </legend>
      <div style={TREE_ROW}>
        <Select
          label={labels.filterTree}
          value={group.combinator}
          part="filter-operator"
          className={classNames.filterOperator}
          fieldClassName={classNames.filterField}
          labelClassName={classNames.filterLabel}
          options={filterTreeCombinatorOptions(labels)}
          onChange={(next) => onCombinator(path, next)}
        />
        {path.length > 0 ? (
          <Button
            label={labels.filterRemoveGroup}
            part="filter-tree-remove"
            className={classNames.filterTreeRemove}
            onClick={() => onRemove(path)}
          />
        ) : null}
      </div>
      {group.conditions.map((node, index) => {
        const childPath = [...path, index];
        if (isFilterGroup(node)) {
          return (
            <GroupView
              key={childPath.join(".")}
              group={node}
              path={childPath}
              defs={defs}
              labels={labels}
              classNames={classNames}
              registry={registry}
              slots={slots}
              onCombinator={onCombinator}
              onAddCondition={onAddCondition}
              onAddGroup={onAddGroup}
              onReplace={onReplace}
              onRemove={onRemove}
            />
          );
        }
        return (
          <ConditionRow
            key={childPath.join(".")}
            condition={node}
            path={childPath}
            defs={defs}
            labels={labels}
            classNames={classNames}
            registry={registry}
            slots={slots}
            onReplace={onReplace}
            onRemove={onRemove}
          />
        );
      })}
      <GroupActions
        labels={labels}
        classNames={classNames}
        slots={slots}
        onAddCondition={() => onAddCondition(path)}
        onAddGroup={() => onAddGroup(path)}
      />
    </fieldset>
  );
}

/**
 * Recursive AND/OR layout over `QueryFilterGroup`. Writes the
 * versioned `ft` param through `source.setFilterTree`. Adapters supply
 * the kit controls via {@link FilterTreeSlots}.
 *
 * @public
 */
export function FilterTreeChrome<TRow>({
  defs,
  source,
  labels: labelOverrides,
  classNames = {},
  registry = defaultFilterRegistry,
  slots,
  defaultExpanded,
}: Readonly<FilterTreeChromeProps<TRow>>) {
  const labels = resolveLabels(labelOverrides);
  const tree = source.filterTree;
  const commit = source.setFilterTree;
  const first = defs[0];
  const [expanded, setExpanded] = useState(
    () => defaultExpanded === true || Boolean(tree)
  );
  if (!commit || !first || defs.length === 0) return null;
  const Disclosure = slots.Disclosure;

  const actions = filterTreeEditorActions(tree, commit, first, registry);

  return (
    <Disclosure
      label={labels.filterTree}
      expanded={expanded}
      className={classNames.filterTree}
      summaryClassName={classNames.filterTreeSummary}
      onExpandedChange={setExpanded}
    >
      {tree ? (
        <GroupView
          group={tree}
          path={[]}
          defs={defs}
          labels={labels}
          classNames={classNames}
          registry={registry}
          slots={slots}
          onCombinator={actions.setCombinator}
          onAddCondition={actions.addCondition}
          onAddGroup={actions.addGroup}
          onReplace={actions.replace}
          onRemove={actions.remove}
        />
      ) : (
        <GroupActions
          labels={labels}
          classNames={classNames}
          slots={slots}
          onAddCondition={() => actions.addCondition([])}
          onAddGroup={() => actions.addGroup([])}
        />
      )}
    </Disclosure>
  );
}

// packages/angular/angular/src/filters/filterTreeChrome.ts
/**
 * The nested AND/OR filter builder's Chrome: the structure — groups inside
 * groups, their conditions, the actions, the labels and the part names —
 * computed from core's filter-tree model. Every control is the kit's: the
 * kit hands its select, input, button and disclosure components in `slots`.
 */
import {
  defaultFilterRegistry,
  type FilterDef,
  filterTreeCombinatorOptions,
  filterTreeConditionModel,
  filterTreeEditorActions,
  type FilterTypeRegistry,
  isFilterGroup,
  type QueryCondition,
  type QueryFilterGroup,
  resolveLabels,
  type TableLabels,
  type TableSource,
} from "@adapttable/core";
import type {
  FilterTreeButtonProps,
  FilterTreeDisclosureProps,
  FilterTreeInputProps,
  FilterTreeSelectProps,
} from "@adapttable/core/binding";
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  signal,
  type TemplateRef,
  type Type,
  viewChild,
} from "@angular/core";

import { AdaptControl } from "../control";

/**
 * The kit's controls for the filter tree. Each is a standalone component
 * with one `props` input: `FilterTreeSelectProps`, `FilterTreeInputProps`,
 * `FilterTreeButtonProps`, and `FilterTreeDisclosureProps` whose `children`
 * is a template the disclosure renders when open.
 *
 * @public
 */
export interface FilterTreeSlots {
  /** A choice control. */
  readonly Select: Type<unknown>;
  /** A text, number or date field. */
  readonly Input: Type<unknown>;
  /** An action button. */
  readonly Button: Type<unknown>;
  /** The collapsible Advanced section. */
  readonly Disclosure: Type<unknown>;
}

/**
 * The disclosure's props in Angular: its content is a template.
 *
 * @public
 */
export type AngularFilterTreeDisclosureProps = FilterTreeDisclosureProps<
  TemplateRef<unknown>
>;

/** One control of a condition's value, tagged with the slot that draws it. */
type ValueControl =
  | { readonly slot: "Select"; readonly props: FilterTreeSelectProps }
  | { readonly slot: "Input"; readonly props: FilterTreeInputProps };

/** One condition row, ready to draw. */
interface ConditionView {
  readonly kind: "condition";
  readonly key: string;
  readonly field: FilterTreeSelectProps;
  readonly op: FilterTreeSelectProps | undefined;
  readonly values: readonly ValueControl[];
  readonly remove: FilterTreeButtonProps;
}

/** One AND/OR group, ready to draw. */
interface GroupView {
  readonly kind: "group";
  readonly key: string;
  readonly depth: number;
  readonly legend: string;
  readonly combinator: FilterTreeSelectProps;
  readonly remove: FilterTreeButtonProps | undefined;
  readonly children: readonly (GroupView | ConditionView)[];
  readonly addCondition: FilterTreeButtonProps;
  readonly addGroup: FilterTreeButtonProps;
}

/** What the whole builder draws. */
interface TreeView {
  readonly root: GroupView | undefined;
  readonly addCondition: FilterTreeButtonProps;
  readonly addGroup: FilterTreeButtonProps;
}

/** The value controls for one condition's editor. */
function valueControls(
  editor: NonNullable<ReturnType<typeof filterTreeConditionModel>>["value"],
  labels: Required<TableLabels>,
  onChange: (value: unknown) => void
): ValueControl[] {
  switch (editor.kind) {
    case "none":
      return [];
    case "boolean":
      return [
        {
          slot: "Select",
          props: {
            label: labels.value,
            value: editor.choice,
            part: "filter-select",
            options: editor.options,
            onChange: (next) => {
              onChange(editor.write(next));
            },
          },
        },
      ];
    case "relative": {
      const preset: ValueControl = {
        slot: "Select",
        props: {
          label: labels.opRelative,
          value: editor.preset,
          part: "filter-select",
          options: editor.options,
          onChange: (next) => {
            onChange(editor.writePreset(next));
          },
        },
      };
      if (!editor.counted) return [preset];
      return [
        preset,
        {
          slot: "Input",
          props: {
            label: "N",
            type: "number",
            value: String(editor.n),
            onChange: (next) => {
              onChange(editor.writeCount(next));
            },
          },
        },
      ];
    }
    case "between":
      return [
        {
          slot: "Input",
          props: {
            label: labels.from,
            type: editor.type,
            value: editor.a,
            onChange: (next) => {
              onChange(editor.writeA(next));
            },
          },
        },
        {
          slot: "Input",
          props: {
            label: labels.to,
            type: editor.type,
            value: editor.b,
            onChange: (next) => {
              onChange(editor.writeB(next));
            },
          },
        },
      ];
    case "single":
      return [
        {
          slot: "Input",
          props: {
            label: labels.value,
            type: editor.type,
            value: editor.text,
            onChange: (next) => {
              onChange(editor.write(next));
            },
          },
        },
      ];
  }
}

/** Everything a view builder needs. */
interface BuildContext<TRow> {
  readonly defs: readonly FilterDef<TRow>[];
  readonly labels: Required<TableLabels>;
  readonly registry: FilterTypeRegistry;
  readonly actions: ReturnType<typeof filterTreeEditorActions>;
}

function conditionView<TRow>(
  condition: QueryCondition,
  path: readonly number[],
  context: BuildContext<TRow>
): ConditionView | undefined {
  const { defs, labels, registry, actions } = context;
  const model = filterTreeConditionModel(condition, defs, registry, labels);
  if (!model) return undefined;
  return {
    kind: "condition",
    key: path.join("."),
    field: {
      label: labels.filterField,
      value: model.def.key,
      part: "filter-select",
      options: model.fieldOptions,
      onChange: (key) => {
        const next = model.withField(key);
        if (next) actions.replace(path, next);
      },
    },
    op:
      model.opOptions.length > 0
        ? {
            label: labels.operator,
            value: condition.op,
            part: "filter-operator",
            options: model.opOptions,
            onChange: (op) => {
              actions.replace(path, model.withOp(op));
            },
          }
        : undefined,
    values: valueControls(model.value, labels, (value) => {
      actions.replace(path, model.withValue(value));
    }),
    remove: {
      label: labels.filterRemoveCondition,
      part: "filter-tree-remove",
      onClick: () => {
        actions.remove(path);
      },
    },
  };
}

function groupView<TRow>(
  group: QueryFilterGroup,
  path: readonly number[],
  context: BuildContext<TRow>
): GroupView {
  const { labels, actions } = context;
  const children: (GroupView | ConditionView)[] = [];
  group.conditions.forEach((node, index) => {
    const childPath = [...path, index];
    if (isFilterGroup(node)) {
      children.push(groupView(node, childPath, context));
      return;
    }
    const view = conditionView(node, childPath, context);
    if (view) children.push(view);
  });
  return {
    kind: "group",
    key: path.join("."),
    depth: path.length,
    legend:
      group.combinator === "or"
        ? labels.filterCombinatorOr
        : labels.filterCombinatorAnd,
    combinator: {
      label: labels.filterTree,
      value: group.combinator,
      part: "filter-operator",
      options: filterTreeCombinatorOptions(labels),
      onChange: (next) => {
        actions.setCombinator(path, next);
      },
    },
    remove:
      path.length > 0
        ? {
            label: labels.filterRemoveGroup,
            part: "filter-tree-remove",
            onClick: () => {
              actions.remove(path);
            },
          }
        : undefined,
    children,
    addCondition: {
      label: labels.filterAddCondition,
      onClick: () => {
        actions.addCondition(path);
      },
    },
    addGroup: {
      label: labels.filterAddGroup,
      onClick: () => {
        actions.addGroup(path);
      },
    },
  };
}

/**
 * One AND/OR group and everything inside it, drawn recursively.
 *
 * @internal
 */
@Component({
  selector: "adapt-filter-tree-group",
  imports: [AdaptControl],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let g = group();
    @let s = slots();
    <fieldset
      data-adapttable-part="filter-tree-group"
      [attr.data-depth]="g.depth"
      [style]="g.depth > 0 ? nestedStyle : rootStyle"
    >
      <legend [style]="hiddenStyle">{{ g.legend }}</legend>
      <div [style]="rowStyle">
        <ng-container
          [adaptControl]="s.Select"
          [adaptControlProps]="g.combinator"
        />
        @if (g.remove; as remove) {
          <ng-container
            [adaptControl]="s.Button"
            [adaptControlProps]="remove"
          />
        }
      </div>
      @for (child of g.children; track child.key) {
        @if (child.kind === "group") {
          <adapt-filter-tree-group [group]="child" [slots]="s" />
        } @else {
          <div data-adapttable-part="filter-tree-condition" [style]="rowStyle">
            <ng-container
              [adaptControl]="s.Select"
              [adaptControlProps]="child.field"
            />
            @if (child.op; as op) {
              <ng-container
                [adaptControl]="s.Select"
                [adaptControlProps]="op"
              />
            }
            @for (value of child.values; track $index) {
              <ng-container
                [adaptControl]="s[value.slot]"
                [adaptControlProps]="value.props"
              />
            }
            <ng-container
              [adaptControl]="s.Button"
              [adaptControlProps]="child.remove"
            />
          </div>
        }
      }
      <div data-adapttable-part="filter-tree-actions" [style]="rowStyle">
        <ng-container
          [adaptControl]="s.Button"
          [adaptControlProps]="g.addCondition"
        />
        <ng-container
          [adaptControl]="s.Button"
          [adaptControlProps]="g.addGroup"
        />
      </div>
    </fieldset>
  `,
})
export class AdaptFilterTreeGroup {
  /** The group. */
  readonly group = input.required<GroupView>();
  /** The kit's controls. */
  readonly slots = input.required<FilterTreeSlots>();

  protected readonly rowStyle = {
    display: "flex",
    "flex-wrap": "wrap",
    "align-items": "flex-end",
    gap: "8px",
    "min-width": "0",
  };
  protected readonly rootStyle = {
    display: "flex",
    "flex-direction": "column",
    gap: "8px",
    "min-width": "0",
    position: "relative",
    margin: "0",
    padding: "0",
    border: "none",
    "min-inline-size": "0",
  };
  protected readonly nestedStyle = {
    display: "flex",
    "flex-direction": "column",
    gap: "8px",
    "min-width": "0",
    position: "relative",
    "margin-block-start": "4px",
    "margin-inline-start": "16px",
    "margin-inline-end": "0",
    "padding-block": "8px",
    "padding-inline-start": "12px",
    border: "none",
    "border-inline-start":
      "2px solid color-mix(in srgb, currentColor 22%, transparent)",
    "background-color": "color-mix(in srgb, currentColor 5%, transparent)",
    "min-inline-size": "0",
  };
  protected readonly hiddenStyle = {
    position: "absolute",
    width: "1px",
    height: "1px",
    margin: "-1px",
    padding: "0",
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    "white-space": "nowrap",
    border: "0",
  };
}

/**
 * The builder's view: what {@link AdaptFilterTreeChrome} draws.
 *
 * @internal
 */
@Component({
  selector: "adapt-filter-tree-view",
  imports: [AdaptControl, AdaptFilterTreeGroup, NgTemplateOutlet],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ng-template #content>
      @let v = view();
      @if (v.root; as root) {
        <adapt-filter-tree-group [group]="root" [slots]="slots()" />
      } @else {
        <div
          data-adapttable-part="filter-tree-actions"
          style="display: flex; flex-wrap: wrap; align-items: flex-end; gap: 8px; min-width: 0"
        >
          <ng-container
            [adaptControl]="slots().Button"
            [adaptControlProps]="v.addCondition"
          />
          <ng-container
            [adaptControl]="slots().Button"
            [adaptControlProps]="v.addGroup"
          />
        </div>
      }
    </ng-template>
    @if (disclosure(); as props) {
      <ng-container
        [adaptControl]="slots().Disclosure"
        [adaptControlProps]="props"
      />
    }
  `,
})
export class AdaptFilterTreeView<TRow> {
  /** The definitions the builder offers. */
  readonly defs = input.required<readonly FilterDef<TRow>[]>();
  /** Reads and writes the filter tree. */
  readonly source =
    input.required<Pick<TableSource<TRow>, "filterTree" | "setFilterTree">>();
  /** Label overrides. */
  readonly labels = input<TableLabels>();
  /** Custom filter types, beyond the built-ins. */
  readonly registry = input<FilterTypeRegistry>(defaultFilterRegistry);
  /** Open the Advanced section on first paint. */
  readonly defaultExpanded = input(false);
  /** The kit's controls. */
  readonly slots = input.required<FilterTreeSlots>();

  private readonly content =
    viewChild.required<TemplateRef<unknown>>("content");
  private readonly toggled = signal<boolean | undefined>(undefined);
  private readonly resolved = computed(() => resolveLabels(this.labels()));

  protected readonly view = computed((): TreeView => {
    const defs = this.defs();
    const { filterTree: tree, setFilterTree: commit } = this.source();
    const labels = this.resolved();
    const registry = this.registry();
    const first = defs[0];
    const actions =
      commit && first
        ? filterTreeEditorActions(tree, commit, first, registry)
        : undefined;
    return {
      root:
        tree && actions
          ? groupView(tree, [], { defs, labels, registry, actions })
          : undefined,
      addCondition: {
        label: labels.filterAddCondition,
        onClick: () => {
          actions?.addCondition([]);
        },
      },
      addGroup: {
        label: labels.filterAddGroup,
        onClick: () => {
          actions?.addGroup([]);
        },
      },
    };
  });

  protected readonly disclosure = computed(
    (): AngularFilterTreeDisclosureProps | undefined => {
      const source = this.source();
      if (!source.setFilterTree || this.defs().length === 0) return undefined;
      const expanded =
        this.toggled() ??
        (this.defaultExpanded() || source.filterTree !== undefined);
      return {
        label: this.resolved().filterTree,
        expanded,
        children: this.content(),
        onExpandedChange: (next) => {
          this.toggled.set(next);
        },
      };
    }
  );
}

/**
 * The nested AND/OR filter builder: the structure is here, every control is
 * the kit's. Renders nothing without definitions or a filter tree to write.
 *
 * @public
 */
@Component({
  selector: "adapt-filter-tree-chrome",
  imports: [AdaptFilterTreeView],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    <adapt-filter-tree-view
      [defs]="defs()"
      [source]="source()"
      [labels]="labels()"
      [registry]="registry()"
      [defaultExpanded]="defaultExpanded()"
      [slots]="slots()"
    />
  `,
})
export class AdaptFilterTreeChrome<TRow> {
  /** The definitions the builder offers. */
  readonly defs = input.required<readonly FilterDef<TRow>[]>();
  /** Reads and writes the filter tree. */
  readonly source =
    input.required<Pick<TableSource<TRow>, "filterTree" | "setFilterTree">>();
  /** Label overrides. */
  readonly labels = input<TableLabels>();
  /** Custom filter types, beyond the built-ins. */
  readonly registry = input<FilterTypeRegistry>(defaultFilterRegistry);
  /** Open the Advanced section on first paint. */
  readonly defaultExpanded = input(false);
  /** The kit's controls. */
  readonly slots = input.required<FilterTreeSlots>();
}
