// packages/angular/adapter-angular-unstyled/src/components/paginationFooter.ts
/**
 * Row count and the windowed pager.
 */
import { ChangeDetectionStrategy, Component, input } from "@angular/core";

import type { TableView } from "../dataTable";

/**
 * Prev/next pager with a rows-per-page select.
 *
 * @internal
 */
@Component({
  selector: "adapt-pagination-footer",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: "display: contents" },
  template: `
    @let v = view();
    <div data-adapttable-part="footer">
      <label>
        {{ v.table.labels().rowsPerPage }}
        <select
          data-adapttable-part="rows-per-page"
          [attr.aria-label]="v.table.labels().rowsPerPage"
          [value]="v.table.source().limit"
          (change)="v.table.setLimit(+$any($event.target).value)"
        >
          @for (size of v.table.pageSizeOptions(); track size) {
            <option [value]="size">{{ size }}</option>
          }
        </select>
      </label>
      @if (v.table.source().total > 0) {
        <span>{{
          v.table.labels().showing({
            from: v.table.pagination().fromIndex,
            to: v.table.pagination().toIndex,
            total: v.table.source().total,
          })
        }}</span>
      }
      <div data-adapttable-part="pager">
        <span>{{
          v.table.labels().pageOf({
            page: v.table.pagination().safePage,
            total: v.table.pagination().totalPages,
          })
        }}</span>
        <button
          type="button"
          data-adapttable-part="page-prev"
          [attr.aria-label]="v.table.labels().previousPage"
          [disabled]="v.table.pagination().safePage <= 1"
          (click)="v.table.setPage(v.table.pagination().safePage - 1)"
        >
          ‹
        </button>
        @for (slot of v.table.pagerSlots(); track slot.key) {
          @if (slot.item === "ellipsis") {
            <span data-adapttable-part="page-ellipsis" aria-hidden="true"
              >…</span
            >
          } @else {
            <button
              type="button"
              data-adapttable-part="page-number"
              [attr.aria-current]="
                slot.item === v.table.pagination().safePage ? 'page' : null
              "
              (click)="v.table.setPage(+slot.item)"
            >
              {{ slot.item }}
            </button>
          }
        }
        <button
          type="button"
          data-adapttable-part="page-next"
          [attr.aria-label]="v.table.labels().nextPage"
          [disabled]="
            v.table.pagination().safePage >= v.table.pagination().totalPages
          "
          (click)="v.table.setPage(v.table.pagination().safePage + 1)"
        >
          ›
        </button>
      </div>
    </div>
  `,
})
export class AdaptPaginationFooter<TRow> {
  /** What the table renders from. */
  readonly view = input.required<TableView<TRow>>();
}

// packages/react/adapter-bootstrap/src/components/PaginationFooter.tsx
import {
  pageSizeOptions,
  type PaginationInfo,
  paginationSlots,
  type TableLabels,
} from "@adapttable/react/adapter";
import { Form, Pagination } from "react-bootstrap";

export function Footer({
  pagination,
  total,
  limit,
  setPage,
  setLimit,
  labels,
  className,
  showRowsPerPage = true,
}: Readonly<{
  pagination: PaginationInfo;
  total: number;
  limit: number;
  setPage: (n: number) => void;
  setLimit: (n: number) => void;
  labels: Required<TableLabels>;
  className?: string;
  showRowsPerPage?: boolean;
}>) {
  const { safePage, totalPages, fromIndex, toIndex } = pagination;

  return (
    <div
      className={`d-flex justify-content-between align-items-center flex-wrap gap-3 ${className ?? ""}`}
    >
      <div className="d-flex align-items-center gap-2">
        {showRowsPerPage && (
          <>
            <span className="small text-body-secondary">
              {labels.rowsPerPage}
            </span>

            <Form.Select
              size="sm"
              aria-label={labels.rowsPerPage}
              value={String(limit)}
              onChange={(e) => setLimit(Number(e.target.value))}
              style={{ width: "72px" }}
            >
              {pageSizeOptions(limit).map((n) => (
                <option key={n} value={String(n)}>
                  {n}
                </option>
              ))}
            </Form.Select>
          </>
        )}

        {total > 0 && (
          <span className="small text-body-secondary">
            {labels.showing({ from: fromIndex, to: toIndex, total })}
          </span>
        )}
      </div>

      <div className="d-flex align-items-center gap-2">
        <span className="small text-body-secondary">
          {labels.pageOf({ page: safePage, total: totalPages })}
        </span>

        <Pagination size="sm" className="mb-0">
          <Pagination.Prev
            aria-label={labels.previousPage}
            disabled={safePage <= 1}
            onClick={() => setPage(safePage - 1)}
          />

          {paginationSlots(safePage, totalPages).map(({ item, key }) =>
            item === "ellipsis" ? (
              <Pagination.Ellipsis key={key} disabled />
            ) : (
              <Pagination.Item
                key={key}
                active={item === safePage}
                aria-current={item === safePage ? "page" : undefined}
                onClick={() => setPage(item)}
              >
                {item}
              </Pagination.Item>
            )
          )}

          <Pagination.Next
            aria-label={labels.nextPage}
            disabled={safePage >= totalPages}
            onClick={() => setPage(safePage + 1)}
          />
        </Pagination>
      </div>
    </div>
  );
}
