// packages/react/react/src/rows/rowReorder.ts
/**
 * Row reordering — the React binding.
 *
 * Core's reorder engine owns the grab model (Space lifts, arrows move, Space
 * drops, Escape cancels, each step announced), drag and drop, and the
 * resolution of grouped and tree moves. This module subscribes to it, hands it
 * React's drag and key events, and keeps the React-typed state and the drop
 * styling the kits apply. The table never mutates the array;
 * `onRowReorder(from, to, row)` is the same one-way write as `onCellEdit`.
 */
import {
  createRowReorderController,
  isRowMovePending,
  type RowDropPosition,
  type RowReorderControllerOptions,
  rowReorderRowAttributes,
} from "@adapttable/core";
import {
  rowReorderDropStyle as coreRowReorderDropStyle,
  rowReorderSignature as coreRowReorderSignature,
  type RowReorderState as NeutralRowReorderState,
} from "@adapttable/core/binding";
import {
  type CSSProperties,
  type DragEvent,
  type KeyboardEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
  useSyncExternalStore,
} from "react";

export {
  applyRowReorder,
  datasetIndex,
  REORDER_COLUMN_KEY,
  type RowReorderDecision,
  type RowReorderHandler,
  type RowReorderLabels,
} from "@adapttable/core";
export { REORDER_COLUMN_WIDTH } from "@adapttable/core/binding";
export { ROW_DND_MIME } from "@adapttable/core/binding";

/** How far a lifted row is dimmed while it is being dragged. */
export const ROW_REORDER_LIFTED_OPACITY = 0.45;

/**
 * Dim the lifted row and draw an insertion line on the drop target.
 * Kits apply this so a host without CSS still sees the gesture; unstyled
 * hosts can also target `data-dragging` / `data-drop` from classNames.
 *
 * @public
 */
export function rowReorderDropStyle(
  attrs: { "data-dragging"?: ""; "data-drop"?: RowDropPosition } | undefined
): CSSProperties {
  return coreRowReorderDropStyle(attrs);
}

/**
 * Headless reorder state returned by `useRowReorder` — `@adapttable/core`'s
 * `RowReorderState` with React's drag and key events.
 *
 * @public
 */
export type RowReorderState<TRow> = NeutralRowReorderState<
  TRow,
  DragEvent<HTMLElement>,
  KeyboardEvent<HTMLElement>
>;

/**
 * Per-row digest so a memoized row repaints when IT is lifted or is the drop
 * target. The `L` bit is global — `reorder.lifted !== null` — so every visible
 * row also repaints once when a drag starts and once when it ends. Without it
 * a neighbour keeps a stale `dropProps` that closed over `lifted === null`,
 * `onDragOver` never calls `preventDefault()`, and Chromium fires `dragend`
 * instead of `drop`. Hover (`overIndex`) still does not repaint untouched
 * rows; the extra cost is one visible-row pass per drag lifecycle, which is
 * the point of this digest.
 *
 * @public
 */
export function rowReorderSignature<TRow>(
  reorder: RowReorderState<TRow> | undefined,
  rowId: string,
  localIndex: number
): string | null {
  // One digest, defined by the engine: a binding that wrote its own would
  // drift from the one the memo comparator on the other side reads.
  return coreRowReorderSignature(reorder, rowId, localIndex);
}

/**
 * Headless row reorder. Inert until the host passes a `RowReorderHandler`;
 * omit it and this hook still runs (Rules of Hooks) but every builder no-ops.
 *
 * The grab model, drag and drop, the mobile swap and the move confirmation
 * live in core's reorder controller; this hook subscribes to it and hands it
 * React's drag and key events.
 *
 * @public
 */
export function useRowReorder<TRow>(
  options: RowReorderControllerOptions<TRow>
): RowReorderState<TRow> {
  const { enabled, getRowId } = options;
  const [controller] = useState(() => createRowReorderController(options));
  controller.configure(options);
  const {
    lifted,
    overIndex,
    overPosition,
    pendingMove,
    hostConfirmPending,
    announcement,
  } = useSyncExternalStore(
    controller.subscribe,
    controller.getSnapshot,
    controller.getSnapshot
  );

  useEffect(() => controller.connect(), [controller]);

  const dragProps = useCallback<RowReorderState<TRow>["dragProps"]>(
    (rowId, localIndex) => ({
      draggable: true,
      onDragStart: (event) => {
        controller.dragStart(event, rowId, localIndex);
      },
      onDragEnd: controller.dragEnd,
    }),
    [controller]
  );

  const dropProps = useCallback<RowReorderState<TRow>["dropProps"]>(
    (localIndex, row, windowStart) => ({
      onDragOver: (event) => {
        controller.dragOver(event, localIndex);
      },
      onDrop: (event) => {
        controller.drop(event, localIndex, row, windowStart);
      },
    }),
    [controller]
  );

  const handleKeyDown = useCallback<RowReorderState<TRow>["handleKeyDown"]>(
    (event, rowId, localIndex, row, windowStart, rowCount) => {
      controller.keyDown(event, {
        rowId,
        localIndex,
        row,
        windowStart,
        rowCount,
      });
    },
    [controller]
  );

  const isLifted = useCallback(
    (rowId: string) => lifted?.rowId === rowId,
    [lifted]
  );
  const isMovePending = useCallback(
    (row: TRow) => isRowMovePending(pendingMove, row, getRowId),
    [getRowId, pendingMove]
  );

  const rowAttrs = useCallback<RowReorderState<TRow>["rowAttrs"]>(
    (rowId, localIndex) =>
      rowReorderRowAttributes(
        { lifted, overIndex, overPosition },
        rowId,
        localIndex
      ),
    [lifted, overIndex, overPosition]
  );

  return useMemo(
    () => ({
      lifted,
      overIndex,
      overPosition,
      pendingMove,
      hostConfirmPending,
      announcement: enabled ? announcement : "",
      isLifted,
      isMovePending,
      dragProps,
      dropProps,
      handleKeyDown,
      moveBy: controller.moveBy,
      moveMenu: controller.moveMenu,
      selectMoveTarget: controller.selectMoveTarget,
      confirmMove: controller.confirmMove,
      cancelMove: controller.cancelMove,
      rowAttrs,
    }),
    [
      controller,
      lifted,
      overIndex,
      overPosition,
      pendingMove,
      hostConfirmPending,
      enabled,
      announcement,
      isLifted,
      isMovePending,
      dragProps,
      dropProps,
      handleKeyDown,
      rowAttrs,
    ]
  );
}

// packages/angular/angular/src/rows/rowReorder.ts
/**
 * Row reordering for Angular: core's grab / drag / keyboard model, published
 * as a signal so the grip and drop targets stay in sync with the table.
 */
import {
  createRowReorderController,
  isRowMovePending,
  type RowDragEvent,
  type RowKeyEvent,
  rowReorderRowAttributes,
  rowReorderRuntimeOptions,
  type TableSource,
} from "@adapttable/core";
import { type RowReorderState as NeutralRowReorderState } from "@adapttable/core/binding";
import {
  assertInInjectionContext,
  computed,
  DestroyRef,
  effect,
  inject,
  Injector,
  type Signal,
} from "@angular/core";

import type { DataTable } from "../dataTable";
import type { AdaptTableFeature } from "../featureHost";
import type { RowReorderFeature } from "../features/rowReorder";
import { tableRuntimeFor } from "../layout/tableRuntime";
import { fromStore } from "../store";

/**
 * Headless reorder state — core's contract with Angular's drag and key events.
 *
 * @public
 */
export type RowReorderState<TRow> = NeutralRowReorderState<
  TRow,
  DragEvent,
  KeyboardEvent
>;

/**
 * Options for {@link injectRowReorder}.
 *
 * @public
 */
export interface RowReorderStateOptions<TRow> {
  /** The headless table. */
  readonly table: DataTable<TRow>;
  /** The live source the controller reads rows from. */
  readonly source: Signal<TableSource<TRow>>;
  /** The composed features; the reorder seeds from the one with id `row-reorder`. */
  readonly features: readonly AdaptTableFeature[];
  /** The injector to run effects in. */
  readonly injector?: Injector;
}

function rowReorderFeatureOf<TRow>(
  features: readonly AdaptTableFeature[]
): RowReorderFeature<TRow> | undefined {
  return features.find(
    (feature): feature is RowReorderFeature<TRow> =>
      feature.id === "row-reorder"
  );
}

function asDrag(event: DragEvent): RowDragEvent {
  return event as unknown as RowDragEvent;
}

function asKey(event: KeyboardEvent): RowKeyEvent {
  return event as unknown as RowKeyEvent;
}

/**
 * The live reorder state when {@link rowReorder} is composed. Absent
 * otherwise — the grip draws nothing.
 *
 * @param options - See {@link RowReorderStateOptions}.
 * @returns The state as a signal, or `undefined` when the feature is off.
 *
 * @public
 */
export function injectRowReorder<TRow>(
  options: RowReorderStateOptions<TRow>
): Signal<RowReorderState<TRow>> | undefined {
  const feature = rowReorderFeatureOf<TRow>(options.features);
  if (!feature) return undefined;
  if (!options.injector) assertInInjectionContext(injectRowReorder);
  const injector = options.injector ?? inject(Injector);
  const destroyRef = injector.get(DestroyRef);
  const runtime = tableRuntimeFor(
    options.table,
    options.source,
    options.features
  );
  const controllerOptions = () =>
    rowReorderRuntimeOptions(runtime, feature.onRowReorder, feature.options);
  const controller = createRowReorderController<TRow>(controllerOptions());
  effect(
    () => {
      controller.configure(controllerOptions());
    },
    { injector }
  );
  destroyRef.onDestroy(controller.connect());

  const snapshot = fromStore(controller, { injector });
  return computed((): RowReorderState<TRow> => {
    const {
      lifted,
      overIndex,
      overPosition,
      pendingMove,
      hostConfirmPending,
      announcement,
    } = snapshot();
    return {
      lifted,
      overIndex,
      overPosition,
      pendingMove,
      hostConfirmPending,
      announcement,
      isLifted: (rowId) => lifted?.rowId === rowId,
      isMovePending: (row) =>
        isRowMovePending(
          pendingMove,
          row,
          (entry) => runtime.view()?.getRowId(entry) ?? ""
        ),
      dragProps: (rowId, localIndex) => ({
        draggable: true,
        onDragStart: (event) => {
          controller.dragStart(asDrag(event), rowId, localIndex);
        },
        onDragEnd: () => {
          controller.dragEnd();
        },
      }),
      dropProps: (localIndex, row, windowStart) => ({
        onDragOver: (event) => {
          controller.dragOver(asDrag(event), localIndex);
        },
        onDrop: (event) => {
          controller.drop(asDrag(event), localIndex, row, windowStart);
        },
      }),
      handleKeyDown: (event, rowId, localIndex, row, windowStart, rowCount) => {
        controller.keyDown(asKey(event), {
          rowId,
          localIndex,
          row,
          windowStart,
          rowCount,
        });
      },
      moveBy: controller.moveBy,
      moveMenu: controller.moveMenu,
      selectMoveTarget: controller.selectMoveTarget,
      confirmMove: controller.confirmMove,
      cancelMove: controller.cancelMove,
      rowAttrs: (rowId, localIndex) =>
        rowReorderRowAttributes(
          { lifted, overIndex, overPosition },
          rowId,
          localIndex
        ),
    };
  });
}
