// packages/angular/adapter-angular-unstyled/src/components/savedViewsMenu.ts
/**
 * The saved-views menu: a button and a panel listing the saved views —
 * click one to apply it, or delete it — above a row that saves the table's
 * current state under a name.
 */
import {
  injectSavedViews,
  type SavedViewsControllerOptions,
  type SavedViewsSlotProps,
  type SavedViewsState,
} from "@adapttable/angular";
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  type ElementRef,
  inject,
  Injector,
  input,
  type OnInit,
  signal,
  viewChild,
} from "@angular/core";

import { MENU_PANEL_STYLE, menuPopover } from "./menuPopover";

/**
 * The saved-views toolbar control.
 *
 * @internal
 */
@Component({
  selector: "adapt-saved-views-menu",
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let l = props().labels;
    <div #root data-adapttable-part="views-menu" style="position: relative">
      <button
        #trigger
        type="button"
        aria-haspopup="true"
        data-adapttable-part="views-button"
        style="flex-shrink: 0; white-space: nowrap"
        [attr.aria-expanded]="popover.open()"
        [attr.data-active]="popover.open() ? '' : null"
        (click)="popover.toggle()"
      >
        {{ l.savedViews }}
      </button>
      @if (popover.open()) {
        <div #panel data-adapttable-part="views-panel" [style]="panelStyle">
          @for (view of views()?.views() ?? []; track view.name) {
            <div data-adapttable-part="views-row" [style]="rowStyle">
              <button
                type="button"
                data-adapttable-part="views-item"
                (click)="apply(view.name)"
              >
                {{ view.name }}
              </button>
              <button
                type="button"
                data-adapttable-part="views-delete"
                [attr.aria-label]="l.deleteView + ': ' + view.name"
                (click)="views()?.remove(view.name)"
              >
                ×
              </button>
            </div>
          }
          <hr data-adapttable-part="views-divider" />
          <div data-adapttable-part="views-save-row" [style]="rowStyle">
            <input
              data-adapttable-part="views-input"
              [attr.aria-label]="l.viewName"
              [attr.placeholder]="l.viewName"
              [value]="name()"
              (input)="name.set($any($event.target).value)"
            />
            <button
              type="button"
              data-adapttable-part="views-save"
              [disabled]="trimmed() === ''"
              (click)="save()"
            >
              {{ l.saveView }}
            </button>
          </div>
        </div>
      }
    </div>
  `,
})
export class AdaptSavedViewsMenu implements OnInit {
  /** The slot's props. */
  readonly props =
    input.required<SavedViewsSlotProps<SavedViewsControllerOptions>>();

  protected readonly panelStyle = MENU_PANEL_STYLE;
  protected readonly rowStyle = {
    display: "flex",
    "align-items": "center",
    gap: "6px",
  };
  protected readonly name = signal("");
  protected readonly trimmed = computed(() => this.name().trim());
  /** The views, once the props say where they are kept. */
  protected readonly views = signal<SavedViewsState | undefined>(undefined);

  private readonly injector = inject(Injector);
  private readonly root = viewChild<ElementRef<HTMLElement>>("root");
  private readonly trigger = viewChild<ElementRef<HTMLElement>>("trigger");
  private readonly panel = viewChild<ElementRef<HTMLElement>>("panel");
  protected readonly popover = menuPopover(
    {
      root: () => this.root()?.nativeElement,
      trigger: () => this.trigger()?.nativeElement,
      panel: () => this.panel()?.nativeElement,
    },
    this.injector
  );

  /** Open the views where the props say they are kept. */
  ngOnInit(): void {
    this.views.set(
      injectSavedViews({ ...this.props().options, injector: this.injector })
    );
  }

  protected apply(name: string): void {
    this.views()?.apply(name);
    this.popover.close();
  }

  protected save(): void {
    this.views()?.save(this.trimmed());
    this.name.set("");
  }
}

// packages/react/adapter-mantine/src/components/SavedViewsMenu.tsx
import { useSavedViews, type UseSavedViewsOptions } from "@adapttable/react";
import { type TableLabels, useEscapeClose } from "@adapttable/react/adapter";
import {
  ActionIcon,
  Box,
  Button,
  Divider,
  Group,
  Popover,
  TextInput,
} from "@mantine/core";
import { useState } from "react";

import { CloseIcon } from "../icons";

/**
 * The label strings the saved-views menu renders.
 *
 * @public
 */
export type SavedViewsLabels = Pick<
  Required<TableLabels>,
  "savedViews" | "saveView" | "viewName" | "deleteView"
>;

/**
 * Props for {@link SavedViewsMenu}.
 *
 * @public
 */
export interface SavedViewsMenuProps {
  /** Storage + URL backend wiring, forwarded to core's `useSavedViews`. */
  options: UseSavedViewsOptions;
  /** Resolved table labels (trigger, save row, delete action). */
  labels: SavedViewsLabels;
}

/**
 * Saved-views menu: lists every captured view (click a name to apply it and
 * close, the trailing ✕ to delete it) above a save row that captures the
 * table's CURRENT URL state under the typed name. Pairs with core's
 * `useSavedViews` and composes into the `toolbar` slot — or let
 * `<DataTable savedViews>` mount it for you next to the Columns menu.
 *
 * @public
 */
export function SavedViewsMenu({
  options,
  labels,
}: Readonly<SavedViewsMenuProps>) {
  const views = useSavedViews(options);
  const [opened, setOpened] = useState(false);
  const [name, setName] = useState("");
  const trimmed = name.trim();
  useEscapeClose(opened, () => setOpened(false));
  // Saving clears the input but keeps the menu open, so several views can
  // be captured in one sitting.
  const handleSave = () => {
    views.save(trimmed);
    setName("");
  };
  // A Popover, not a Menu: the panel holds buttons and a text input, so
  // `role="menu"` semantics (menuitem children, typeahead) would be a lie.
  return (
    <Popover
      opened={opened}
      onChange={(nextOpened) => {
        if (!nextOpened) setOpened(false);
      }}
      position="bottom-end"
      withinPortal
      returnFocus
      zIndex={10050}
      middlewares={{ flip: false, shift: { padding: 8 } }}
    >
      <Popover.Target>
        <Button
          variant="default"
          size="sm"
          aria-expanded={opened}
          onClick={() => setOpened((value) => !value)}
        >
          {labels.savedViews}
        </Button>
      </Popover.Target>
      <Popover.Dropdown>
        <Box
          p={4}
          miw={220}
          mah="min(70vh, 360px)"
          style={{ overflowY: "auto" }}
        >
          {views.views.map((view) => (
            <Group key={view.name} gap={6} px={4} py={2} wrap="nowrap">
              <Button
                variant="subtle"
                size="compact-sm"
                justify="flex-start"
                style={{ flex: 1 }}
                onClick={() => {
                  views.apply(view.name);
                  setOpened(false);
                }}
              >
                {view.name}
              </Button>
              <ActionIcon
                variant="subtle"
                color="gray"
                size="sm"
                aria-label={`${labels.deleteView}: ${view.name}`}
                onClick={() => views.remove(view.name)}
              >
                <CloseIcon size={12} />
              </ActionIcon>
            </Group>
          ))}
          <Divider my={4} />
          <Group gap={6} p={4} wrap="nowrap">
            <TextInput
              size="xs"
              style={{ flex: 1 }}
              aria-label={labels.viewName}
              placeholder={labels.viewName}
              value={name}
              onChange={(e) => setName(e.currentTarget.value)}
            />
            <Button size="xs" disabled={trimmed === ""} onClick={handleSave}>
              {labels.saveView}
            </Button>
          </Group>
        </Box>
      </Popover.Dropdown>
    </Popover>
  );
}
